### ISSUE TITLE
PL Language

### ISSUE THREAD

**Issue by jacc555** [Taapat/enigma2-plugin-youtube#100]
Hi. can you update polish language?
[PL](https://drive.google.com/file/d/1FvfmGManNMU_7BmJX_N5EiMiJTbJsPsN/view?usp=drivesdk)

**Comment by Taapat** [comment]
@jacc555 can you check ort this is correct: https://github.com/Taapat/enigma2-plugin-youtube/commit/15d4150256e45a7ecca2e001c5eaf15f0231c39a

**Comment by jacc555** [comment]
@Taapat this is correct. thanks
