### ISSUE TITLE
No Json

### ISSUE THREAD

**Issue by axes1893** [Taapat/enigma2-plugin-youtube#104]
This message appears: No Json object could be decoded.
Thank you, explain to me how to resolve this situation

**Comment by Taapat** [comment]
Could you indicate the specific video in which this error occurs.

**Comment by axes1893** [comment]
Thanks for responding and not being more specific. I have this working on enigma2, with API_KEY; API_CLIENT_ID; API_CLIENT_SECRET for over a year.
Does not work on all channels
