### ISSUE TITLE
Missing titles and description for some videos

### ISSUE THREAD

**Issue by Lishoo** [Taapat/enigma2-plugin-youtube#106]
Hi, I've noticed that for some videos there is no description and no title like search for "jagodki"

![problem1](https://user-images.githubusercontent.com/1045996/97985222-4a341200-1dd8-11eb-8a47-2d2ff2ad93f1.jpg)

![problem2](https://user-images.githubusercontent.com/1045996/97985229-4dc79900-1dd8-11eb-8bf4-3133db67ae6d.jpg)

![1_0_16_10E5_3E8_13E_820000_0_0_0](https://user-images.githubusercontent.com/1045996/97985244-51f3b680-1dd8-11eb-9d1f-846ca76145a0.jpg)

![problem3](https://user-images.githubusercontent.com/1045996/97985250-53bd7a00-1dd8-11eb-93a1-318674a2f04e.jpg)

![problem4](https://user-images.githubusercontent.com/1045996/97985257-56b86a80-1dd8-11eb-81f7-970596eda72a.jpg)

**Comment by Taapat** [comment]
Hi,
In your screenshots I see that you are missing every clip thubnails.
This means that you have some internet speed or connection problems.
I assume this is the reason why you are not shown full information.
I dont have such a problem:
![screenshot1](https://user-images.githubusercontent.com/1623947/98139921-73829a00-1ecd-11eb-85b1-2e02e5e22314.jpg)
![screenshot](https://user-images.githubusercontent.com/1623947/98139935-78dfe480-1ecd-11eb-90cd-f482b43582b3.jpg)

But maybe I missed something.

**Comment by Lishoo** [comment]
Hi, I really don't know why the thumbnails don't show in the list, I saw them only once, while I went to settings, and then back they showed up.
I've fixed the title and description by adding 2 lines of code, you could check them and eventual merge it into the main code as they should not brake anything.

![fix](https://user-images.githubusercontent.com/1045996/98297183-4eb52200-1fb4-11eb-854e-5d9625efc600.jpg)
![fix1](https://user-images.githubusercontent.com/1045996/98297158-478e1400-1fb4-11eb-90d0-1c51464009cc.jpg)
![fix2](https://user-images.githubusercontent.com/1045996/98297200-55dc3000-1fb4-11eb-845b-7057ebfa5bc7.jpg)
![fix3](https://user-images.githubusercontent.com/1045996/98297495-caaf6a00-1fb4-11eb-8b6d-dd023c92031e.jpg)


And something that is still bugged:

![nofix](https://user-images.githubusercontent.com/1045996/98297276-74dac200-1fb4-11eb-8e96-928da20b8f49.jpg)
