### ISSUE TITLE
Login to google account !!

### ISSUE THREAD

**Issue by fairbird** [Taapat/enigma2-plugin-youtube#111]
After latest update before 5 days ago ... The plugin can not login to google account ...
I have reset the API keys more than once but still same things ..

![Selection_001](https://user-images.githubusercontent.com/1761779/105748098-b2ffd600-5f52-11eb-8991-b465dd6586e9.png)

**Comment by Taapat** [comment]
What do you mean by reset the API keys?
If you use your keys, have you verified them on google?
Google has set stricter rules and no longer allows unverified keys.
Use plugin keys.
1. In the plugin settings disable login on startup.
2. Delete /etc/enigma2/YouTube.key.
3. Restart enigma2.
4. In the plugin settings enable login on startup and perform authentication allowing the plugin to use your youtube data.

**Comment by fairbird** [comment]
> What do you mean by reset the API keys?

This what I mean (Before I did that steps and I can login to google account) 
This is old screenshots before one Month ago 
![Selection_002](https://user-images.githubusercontent.com/1761779/105830785-f734ba00-5fd6-11eb-9246-4b421080c7d2.png)
![Selection_003](https://user-images.githubusercontent.com/1761779/105830792-f8fe7d80-5fd6-11eb-8003-8165b5989396.png)
![Selection_004](https://user-images.githubusercontent.com/1761779/105830795-f9971400-5fd6-11eb-8ee1-e0ce1b0796ca.png)



> * In the plugin settings disable login on startup.
> * Delete /etc/enigma2/YouTube.key.
> * Restart enigma2.
> * In the plugin settings enable login on startup and perform authentication allowing the plugin to use your youtube data.

After Your steps as screenshot show login to google account done without error

![Selection_005](https://user-images.githubusercontent.com/1761779/105831501-d7ea5c80-5fd7-11eb-8c22-1106996c1741.png)
![Selection_006](https://user-images.githubusercontent.com/1761779/105831506-d91b8980-5fd7-11eb-9742-81f4a6579e1a.png)

But plugin for search or for feeds not working (Because As you advice I deleted /etc/enigma2/YouTube.key)

![11](https://user-images.githubusercontent.com/1761779/105831747-27c92380-5fd8-11eb-8377-603e08768325.jpg)

But After return back my YouTube.key to /etc/enigma2 search and play video works again but Feeds won't work I have got (same error warring message)

unverified keys

**Comment by Taapat** [comment]
1. Are you really correct finishing plugin authentication?
After gaining access the plugin needs to return in the settings window and you need to save the settings.
If you return the YouTube.key file and you get the plugin running without re-authentication, it means that you have not completed the plugin key authentication.

2. You must select TVs and limited input devices.
But to perform key verification, several conditions must be met https://developers.google.com/youtube/terms/developer-policies#d-accessing-youtube-api-services
and pass the audit on youtube.

**Comment by Taapat** [comment]
If you have problems using plugin keys please show the enigma2 log.
There the reason should be visible.

**Comment by fairbird** [comment]
The log of enigma2 with plugin keys not my keys ...
[enigma.log](https://github.com/Taapat/enigma2-plugin-youtube/files/5875228/enigma.log)
-First tine works ok ..
-After close plugin and open it again I got ([YouTubeApi] error in get response ('The read operation timed out',))

**Comment by Taapat** [comment]
As you can see in the log you have some kind of connection problems.
It seems to me that they are not related to the plugin.


First you get an error in YouTubeApi:
`21:19:48.6697 2021-01-26 21:19:48+0300 [-] [YouTubeApi] error in get response ('The read operation timed out',)`
After that you get the same error in YouTubeSearch get suggestions which does not use any keys:
`21:19:54.7910 2021-01-26 21:19:54+0300 [-] [YouTubeSearch] Error in get suggestions from google <urlopen error ('_ssl.c:711: The handshake operation timed out',)`


This may be a problem with some of your image python components or with your internet connection.

**Comment by fairbird** [comment]
It is ok my friend I fix my keys .. works ok now
You can close this issue ...
![Selection_002](https://user-images.githubusercontent.com/1761779/105892180-8915e480-6022-11eb-836d-b6d42d90b9c5.png)

**Comment by Taapat** [comment]
It seems to me that your problem was not related to keys.
But in any case, I've noticed that google now looking more strictly at the use of unverified keys.
If you have problems with this I recommend using plugin keys.

**Comment by fairbird** [comment]
Of course I have test plugin keys ... And I have got same error as like as with my keys ...
If I Enable (login on startup) then I got (There was an error in creating entry list!) 
And If I Disable (login on startup) and do restart enigma2 plugin works just fine Searching and playing videos ..

Before I don't have this issue with same keys ...
