### ISSUE TITLE
Sound and Subtitles

### ISSUE THREAD

**Issue by axes1893** [Taapat/enigma2-plugin-youtube#139]
Hello good Morning
I'm Portuguese, and since yesterday I started having problems with the videos on youtube.I have KEY+CLIENT ID+CLIENT SECRET API and Vu+zero receiver.

For example this video: https://www.youtube.com/watch?v=hlkb623McOU all songs are "hiccups".
Plus these two subtitled videos: https://www.youtube.com/watch?v=_sDyl0YxUJw
 https://www.youtube.com/watch?v=2NMeax_0Ndw

Subtitles appear late, and it had never happened.
Do you think you can solve it...
Thanks

**Comment by Taapat** [comment]
Or latest version not fix your issues?

**Comment by axes1893** [comment]
Good Morning
I'm using the latest enigma2-plugin-extensions-youtube_h1+git829+c8cfcaa-r0.0_all 16.10.2021.
But unfortunately it doesn't work
Thanks
