### ISSUE TITLE
Crash Related Videos

### ISSUE THREAD

**Issue by thawtes** [Taapat/enigma2-plugin-youtube#143]
hello @Taapat 

new option related videos crash

device: vu duo2
image: openatv 6.4
youtube: logined

thx

LOG
`18:16:10.6854 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2021-10-16 18:16:10+0300 [-]   File "/usr/lib/enigma2/python/Plugins/Extensions/YouTube/YouTubeUi.py", line 549, in splitTaimerStop
18:16:10.6874 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2021-10-16 18:16:10+0300 [-]   File "/usr/lib/enigma2/python/Plugins/Extensions/YouTube/YouTubeUi.py", line 981, in createEntryList
18:16:10.6903 { E } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2021-10-16 18:16:10+0300 [-] TypeError: search_list_full() got an unexpected keyword argument 'relatedToVideoId'
18:16:10.6909 [ E ] python/python.cpp:210 call [ePyObject] (PyObject_CallObject(<bound method YouTubeMain.splitTaimerStop of <class 'Plugins.Extensions.YouTube.YouTubeUi.YouTubeMain'>>,()) failed)`

**Comment by Taapat** [comment]
Ort you completely update the original plugin, or just change individual files?

**Comment by thawtes** [comment]
> Ort you completely update the original plugin, or just change individual files?

only one file.
I will try it completely and give feedback

**Comment by thawtes** [comment]
yes there is no problem. my fault. everything works great.
Sorry, and thank you for your time.
