### ISSUE TITLE
Videos in slow motion

### ISSUE THREAD

**Issue by valdemirjds** [Taapat/enigma2-plugin-youtube#145]
All videos are in slow motion. (Vu+Duo2 - OpenAtv)

**Comment by Taapat** [comment]
Do you use latest version of plugin?
https://github.com/Taapat/enigma2-plugin-youtube/issues/142

**Comment by thawtes** [comment]
> All videos are in slow motion. (Vu+Duo2 - OpenAtv)

videos playing great, update to latest version this plugin
(vu+duo2-openatv)

**Comment by contracer** [comment]
Ok, video running ok with version 843, but when I do a video forward the sound mutes...

**Comment by contracer** [comment]
I disabled the DASH MP4 format and it´s working fine !
Thanks a lot for this project. it´s so usefull to all Enigma2 users !

**Comment by thawtes** [comment]
> Ok, video running ok with version 843, but when I do a video forward the sound mutes...
and @Taapat 
it works very well for me no problem (DASH MP4)
the sound is not muted 
when i forward and rewind the sound is not muted or any other issues

**Comment by Taapat** [comment]
Are you sure that DASH MP4 streams are used?
I noticed that in the ANDROID client, unlike js WEB client before, very many videos are available in mp4 streams.
Therefore, two streams for audio and video are not used in parallel.
