### ISSUE TITLE
MENU - green screen

### ISSUE THREAD

**Issue by kostik12345** [Taapat/enigma2-plugin-youtube#163]
Good evening,
in the new version 970 after pressing MENU green screen ... Image VTI 15.0.0, VU + Solo4K, skin HDGlass16

**Comment by Taapat** [comment]
I hope the latest version works for you.

**Comment by kostik12345** [comment]
Hello, version 972 is already OK. Goodbye

pi 21. 1. 2022 o 7:24 Madars Auns ***@***.***> napísal(a):
