### ISSUE TITLE
After finish/stop a video I end up in 'Download search result. Please wait...' forever screen

### ISSUE THREAD

**Issue by Heart1010** [Taapat/enigma2-plugin-youtube#169]
Everything works like it should, I can search for a video, then play it.... but when it's finish or I press the stop button I end up in a 'Download search result. Please wait...' forever screen - see screenshot

I searched if I can change some setting so the plugin simply goes back to default start page for example when I stop/finish a video but can't find anything related.
So why after stopping a video it goes back to a newly/fresh search screen which takes forever to load (and I mean forever... > 20min and counting) - I can't do anything with my receiver on that time when this happens. (also no terminal connection is possible, no webinterface,... nothing)

![image](https://user-images.githubusercontent.com/1481680/155880781-d86d57a9-42a9-49b3-bfce-55bc10802473.png)

**Comment by Taapat** [comment]
You can set in the plugin settings:
When playback stop: Return to list
When video ends: Return to list

But normally this should not happen because by default happens relevant video search
If search works, this also should work for you.

What is your receiver and image?
Are you using a plugin authenticated in a google account?

**Comment by Heart1010** [comment]
Formuler F1 with pure2 image (v6.3 python2)

> Are you using a plugin authenticated in a google account?

What do you mean here exactly? I generated an 'api/key' with my google account, yes.

**Comment by Taapat** [comment]
I mean if you're in settings enabled Login on startup to log in to your YouTube account.

First try to remove your key and use the plugin key.
The plugin has been aprove in google a while ago and there is no problem with the key limit.
Google has recently set additional rules for private keys, and they may have problems using in google accounts.

**Comment by Taapat** [comment]
Any news?

**Comment by Heart1010** [comment]
So you mean I should:
1) set 'login at startup...' in plugin settings to NO (then save)
2) After that delete my file /etc/enigma2/YouTube.key
3) GUI restart
4) Start your plugin again and set 'login at startup...' back to YES?

**Comment by Taapat** [comment]
First try only 2. and after that 3.
1. and 4. required if you use login at startup.

**Comment by Heart1010** [comment]
looking god now... also re-authent. with your default plugin 
thanks 👍 
 
![image](https://user-images.githubusercontent.com/1481680/156043116-b93edfcb-c5a6-467a-88af-469e58294df7.png)

**Comment by Taapat** [comment]
I understand that I can close this.
