### ISSUE TITLE
Translation of youtube plugin for pt-portugal language ( portuguese )

### ISSUE THREAD

**Issue by nunigaia** [Taapat/enigma2-plugin-youtube#17]
Hi,

Taapat.

Here is my little contribution for your amazing plugin.
Language: Portuguese pt-pt

[po_and_mo.zip](https://github.com/Taapat/enigma2-plugin-youtube/files/448481/po_and_mo.zip)

best regards
shimano

**Comment by Taapat** [comment]
Thank you, I'll add later.

But why do you not want create pull reqest with commit?
In that case, I might add right now.

**Comment by nunigaia** [comment]
Because, i don´t kn.ow how to do it, sorry.

**Comment by Taapat** [comment]
Thank you, added: https://github.com/Taapat/enigma2-plugin-youtube/commit/22a9220b03f9291960bd16da4c4a8a6b792e64e0
