### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\u017e' in position 3030: ordinal not in range(128)

### ISSUE THREAD

**Issue by s3n0** [Taapat/enigma2-plugin-youtube#172]
Hi.

I'm not sure if the issue is with the YouTube plugin or directly with OpenATV 7.1 beta (with Python 3.10.x).

The error occurs when I try to switch the resolution of max. resolution in Youtube plugin configuration from 720p to 1080p and after switching to 1080p I will use the green button or OK button on the RCU.

For OpenATV 6.4, switching from 720p to 1080p maximum YT video resolution works fine. The problem only occurs with OpenATV 7.1.

Here is the crash-log file:
[enigma2_crash_1650482477.log](https://github.com/Taapat/enigma2-plugin-youtube/files/8528238/enigma2_crash_1650482477.log)

Thanks.

**Comment by Taapat** [comment]
Please try on latest plugin version.
In it I removed the ssl key error workaround which affects the encoding.

**Comment by s3n0** [comment]
I use OpenATV and there, however, every update of the Youtube plugin is taken into account. Or no ? 🤔

Should I uninstall the Youtube plugin from OpenATV (from the feed) and install the original Youtube plugin from your github ? In this case, however, I'm afraid something won't work (due to possible incompatibility). 😇

**Comment by Taapat** [comment]
In your log I see that you do not have the latest plugin version which was updated 2 days ago.
How often the OpenATV update plugin feed I do not know.
For the test you need to install the latest version for Python 3: https://github.com/Taapat/enigma2-plugin-youtube/releases/download/git1019/enigma2-plugin-extensions-youtube_py3+git1019+5739c80-r0.0_all.ipk
This should not eliminate any problems.

**Comment by s3n0** [comment]
Thanks. 

It looks like the 720p -> 1080p change settings works (without system crash).

But I have another problem. I should probably create another thread... applies to scrolling (change the video position) youtube videos with 1080p resolution. These videos cannot be moved back and forth (on RCU numeric keys). But ... after switching to 720p maximum resolution video limit, then, these 720p youtube videos can be moved back and forth.

My second problem, however, may also be related to the unofficial youtube API, if I'm not mistaken. Respectively, there is a problem with the 1080p video source limitation - directly from the youtube streaming server. Or am I wrong ? Do 1080p videos work at the same time when trying to move video forward and backward ?

**Comment by Taapat** [comment]
Rewind has nothing to do with the youtube API.
My plugin uses official and google-approved API access.
This is a problem with the DASH MP4 format on enigma, which is used in high resolution.
Try using the serviceapp plugin; https://github.com/Taapat/enigma2-plugin-youtube/issues/57

**Comment by s3n0** [comment]
So, the Youtube-plugin uses the default player configured in the Enigma2 settings ? I thought the Youtube-plugin contained some unique (self) video-player. This is gratifying news that the Youtube-plugin can play online videos in any other player, which I choose in the Enigma2 settings. 

Thanks again.

I will definitely try to use this ExtEplayer as the default player (with Enigma reconfiguration - using the ServiceApp plugin).

_However, at the moment I have a problem (grrrrr... again...) with the OpenATV 7.1 test version... at the point of the ServiceApp installation :). So, I will have to try it on the currently stable version of ATV 6.4 :). Maybe later. But I believe it will work._
