### ISSUE TITLE
Doesn't open any video

### ISSUE THREAD

**Issue by axesPorto** [Taapat/enigma2-plugin-youtube#208]
There was an error in the url of the extracted video:

The following content is not available in this app.

Watch on the latest version of YouTube.?
Rgds

**Comment by axesPorto** [comment]
I have vuzero with Openpli image, and it always worked (2 years) until the day before yesterday...
I have:
API_KEY=
YOUTUBE_API_CLIENT_ID= 
YOUTUBE_API_CLIENT_SECRET=

**Comment by Taapat** [comment]
Hi,
You don't need to use your keys.
Leave the key file unchanged, without data.

Please check network settings, especially dns.

If it doesn't help, please give enigma log or at least give a link to these videos.
All videos witch I try work for me.

**Comment by axesPorto** [comment]
Good afternoon
I deleted all API_KEY
YOUTUBE_API_CLIENT_ID
YOUTUBE_API_CLIENT_SECRET
But the error persists are many videos, possibly send the last ipk works?
Thanks

**Comment by Taapat** [comment]
You can always download the latest versions in releases: https://github.com/Taapat/enigma2-plugin-youtube/releases

If it doesn't help please post here enigma log.

**Comment by axesPorto** [comment]
Thanks for answering
But which ipk should I install the 149KB or 106KB

**Comment by axesPorto** [comment]
> Você sempre pode baixar as versões mais recentes em releases: https://github.com/Taapat/enigma2-plugin-youtube/releases
> 
> Se não ajudar, poste aqui o log do enigma.

Perfect Thank you very much, everything is working fine there
