### ISSUE TITLE
Dreambox two deb

### ISSUE THREAD

**Issue by Freak7x7** [Taapat/enigma2-plugin-youtube#209]
Hallo can you help me please. I will install your plugin on Dreambox two but it doesn't work.
wget https://raw.githubusercontent.com/fairbird/Youtube-Opensource-DreamOS/master/installer.sh -qO - | /bin/sh

Thanks Robert

**Comment by Taapat** [comment]
Sorry, but I don't support dreambox.
As you can see the link from where you install the plugin is not from me.
From where you install the plugin, you should ask about dreambox support.
