### ISSUE TITLE
YT-Feeds Problem

### ISSUE THREAD

**Issue by lanagalice** [Taapat/enigma2-plugin-youtube#214]
there is problem with YTrailer-Feeds

whenever searching for event to get trailer, I got that message
"Problems with YT-Feeds!"

any solution please

**Comment by Taapat** [comment]
Do you report about the problem in this plugin youtube?

**Comment by lanagalice** [comment]
I am reporting now, I report to [Dima73] regard his plugin and he says these part "YT-FEEDS" is belong to you

**Comment by Dima73** [comment]
Madars
Please help.

**Comment by lanagalice** [comment]
Can you help please Mr. Taapat

**Comment by Taapat** [comment]
Check https://github.com/Dima73/enigma2-plugin-extensions-tmbd/pull/36

Please, in the future, invite me to discuss the issue in the repo that has the problem, instead of opening an issue here, where it has nothing to do with it.
