### ISSUE TITLE
Video URL could not be extracted:  Bad request  Video ID [ID of the video]

### ISSUE THREAD

**Issue by Tanbao001** [Taapat/enigma2-plugin-youtube#227]
**Deutsch:**
Hallo! Seit gestern bekomme ich folgende Fehlermeldung:

_Video URL konnte nicht extrahiert werden:
Bad Request
Video ID [ID des Videos]_

Plugin wurde das neueste von Taapat, sowie diverse andere benutzt, doch leider ohne Erfolg.

Box ist eine Vu+ Duo² mit OpenATV 6.4

Viele Grüße
_ _ _ _

**English:**
Hello! Unfortunately since yesterday I'm getting this error below.

_Video URL could not be extracted:  
Bad request  
Video ID [ID of the video]_

The latest plugin from Taapat and various others were used, but unfortunately without success.

Box is a Vu+ Duo² with OpenATV 6.4

Best regards

**Comment by viebrix** [comment]
I have same problem - two days ago I had same error message. After trying to start video again and again it worked. Yesterday, it did not work after all tries.
Maybe could also be a problem with our region (germany/austria/swiss) - I see you speak german...

I tried now to upgrade to newest version - remote per openwebif - but in the console came this error:
Collected errors: * file_md5sum_alloc: Failed to open file /etc/enigma2/YouTube.key: No such file or directory.

Maybe this error is no problem. Do not have currently the chance to check directly on vu+ - maybe later.

**Comment by B24Liberator** [comment]
Yep same problem as you guys  dont think its a region thing since im 
from the UK 
My error 
YouTube plugin there was an error  in extract video url bad request

enigma2 openvix AX HD61 BOX

**Comment by viebrix** [comment]
So firstly the error regarding youtube.key was no real problem. Installation was finished without errors in the gui installation directly on the receiver.

The error:
Video URL could not be extracted:
Bad request
Video ID [ID of the video]
still occurs - also with the most recent version.

I tried for a test to download one part of the video with youtube-dl local on my pc. This is youtube-dl version 2021.12.17 (with nightly built downloaded on 29.July.23) This seems to work. I'm not really sure which youtube-dl version is on my vu+

**Comment by Taapat** [comment]
Thanks for the report!

**Comment by viebrix** [comment]
Many thanks - new version works!

**Comment by gentano** [comment]
Unfortunately the problem occurs again for me since several days :(

Did anybody play around and try to fix the problem? it seems to be related to the spoofed youtube client according to the commit

Im running OpenATV 7.4 on VU UNO 4K.
