### ISSUE TITLE
There is no sound when the DASH is turned on on the Pulse4kmini.

### ISSUE THREAD

**Issue by 68foxboris** [Taapat/enigma2-plugin-youtube#243]
Good day.I thought that this was only a problem with my home build,but it's the same on the openatv 7.4.The receiver is a Pulse4Kmini.The plugin has the maximum resolution the DASH is on.There is video no audio and there is not even a track selection.I reduce the resolution - no change.I turn off the DASH - sound appears,the video resolution becomes 640 by 360.
Here is the plugin's log.
[e2-openatv7.4.log](https://github.com/user-attachments/files/16573129/e2-openatv7.4.log)

**Comment by Taapat** [comment]
Hi,
Hisilicon receivers do not support playing the second stream using the suburi parameter.
The only way is to use exteplayer from plugin serviceapp.
