### ISSUE TITLE
Error: There was an error in extract video URL

### ISSUE THREAD

**Issue by willow5** [Taapat/enigma2-plugin-youtube#245]
I am having this issue with the latest ipk file from here. Please see images below:

![4097_0_1_284_0_0_0_0_0_0_20240926220518](https://github.com/user-attachments/assets/fd2b344e-a151-4061-bc63-6abeddc8f9b3)

![4097_0_1_284_0_0_0_0_0_0_20240926220529](https://github.com/user-attachments/assets/9d6790cd-2423-4111-9e08-058b05e203a8)

**Comment by navinsolanki0807** [comment]
I agree, all links are failing with same error using the latest ipk file.

**Comment by jones873** [comment]
Same Here

**Comment by adisonjohn** [comment]
Same Here
![4097_0_1_1_0_0_0_0_0_0_20240929105733](https://github.com/user-attachments/assets/a4c089f2-3671-4fe8-9827-1dac8fd1ef16)

**Comment by StifflersMom** [comment]
Same here...

**Comment by typer2020** [comment]
Same Here

**Comment by navinsolanki0807** [comment]
Could you send the updated file if possible?

**Comment by nagysifa** [comment]
> YouTubeVideoUrl.py change: line 374: VERSION = '19.39.37' (was: '1.9') line 375: USER_AGENT = 'com.google.android.youtube/%s (Linux; U; Android 11; US) gzip' % VERSION (was: Android 12) line 380: 'androidSdkVersion': 30, (was: 'androidSdkVersion': 31,) line 381: 'clientName': 'ANDROID', (was: 'ANDROID_TESTSUITE',) line 383: 'osVersion': '11', (was: 'osVersion': '12',) line 387: data['params'] = 'Q0FFU0FnZ0M' (was: '2AMB') After these changes in the code, the videos are playing.

This works for me. Thanks!

**Comment by jones873** [comment]
Thank`s also got it working again editing the script, I really hope Taapat is ok he is normally on the ball with this!

**Comment by Orlandoxx** [comment]
Thanx. It works, but I needed to change the media player from Exteplayer to Default Player.

<  2036.700659> 20:11:10.7950 ExtEPlayer3::handleJsonOutput - unhandled key "EPLAYER3_EXTENDED"

**Comment by navinsolanki0807** [comment]
Can someone add the compiled .pyc file of the updated script please.

**Comment by jones873** [comment]
[YouTubeVideoUrl.zip](https://github.com/user-attachments/files/17265377/YouTubeVideoUrl.zip)

**Comment by willow5** [comment]
I updated the YouTubeVideoURL file but now I am getting this screen - can anyone help further please? 
![1_0_19_287B_800_2_11A0000_0_0_0_20241005143619](https://github.com/user-attachments/assets/cc5184f1-87a1-4d73-8a17-71fc005d7009)

**Comment by adisonjohn** [comment]
Now working  https://github.com/Taapat/enigma2-plugin-youtube/releases

**Comment by Taapat** [comment]
Thanks for the report.
I assume that the error in creating entry list is due to the fact that the limit of 3 million connections permitted by the plugin key has recently been exceeded.
Therefore Google has requested me to renew the apy key and perform an audit.
I hope my plugin will not be rejected.
I think I can close this for now.

**Comment by adisonjohn** [comment]
Now working [enigma2-plugin-extensions-youtube_py3-git1294-cbcf8b0-r0.0.ipk 

<img width="551" height="194" alt="Image" src="https://github.com/user-attachments/assets/712e5fdb-f255-4642-8299-78fa259a30ea" />
