### ISSUE TITLE
Problem on latest version

### ISSUE THREAD

**Issue by dacorsa** [Taapat/enigma2-plugin-youtube#248]
Hi guys,
using latest version: Package enigma2-plugin-extensions-youtube (git1229+b237a1e0+b237a1e607-r0) installed in root is up to date.
i see a video stop the audio after half video....i tried many video but i have always the same problem.
If i try to download video i have a file for audio and a file for video.... why?

Thanks best, regards.

**Comment by Taapat** [comment]
Before the change, a client was used that offered several video formats in mp4 format, which contains both video and audio.
This client is no longer working and has been changed.
Now, videos in mp4 format are only available in the lowest resolution.
For other resolutions, the DASH MP4 format is offered, which uses separate streams for video and audio.
If you have problems playing DASH MP4 format, you can try using plugin serviceapp: https://github.com/Taapat/enigma2-plugin-youtube/issues/242
If you want one combined file when downloading, then use the Merge downloaded files option in the settings.

**Comment by dacorsa** [comment]
OK thanks all solved :)
