### ISSUE TITLE
Plugin selects always first audio track instead of default 

### ISSUE THREAD

**Issue by QuarkFermion** [Taapat/enigma2-plugin-youtube#258]
First: Thank you very much @taapat for keeping this plugin running and up to date.

I have noticed that with some videos YouTube adds a bunch of AI translated audio tracks to the genuine default audio track.

It seems the plugin selects automatically the first audio track available which can be a foreign language.

Example:
https://www.youtube.com/watch?v=8scG3KhC6Wo

It would be nice if the plugin would automatically select the original audio track. Of course, a nice enhancement would be if you could select the desired audio language in the settings. 

If this could also be implemented for the download, possibly even both audio tracks, the original audio track and the selected audio track, and merge them together as two selectable tracks, that would be brilliant. 

Thank you very much.

**Comment by Taapat** [comment]
Thanks for the report!
To implement the option to choose languages ​​in the player, so many changes would have to be made that I don't want to do it.
For now, multiple languages ​​are only available for certain videos.

**Comment by QuarkFermion** [comment]
Thanks for the reply. That's understandable, but would it be possible to determine the default (original) audio track and select this one automatically for playbacks and downloads?

At the moment the plugin will always select an auto translated audio track if there is one available. I assume it is the first audio track the plugin finds (haven't had a look into the code).

This weird auto translation is a new YouTube feature and many channels will be automatically selected for auto translation in time. So more and more videos will be affected.

It would be very nice if you were able to have a look into it.

Thanks again for your great work.

19.12.2024 20:38:44 Madars Auns ***@***.***>:

Thanks for the report!
To implement the option to choose languages ​​in the player, so many changes would have to be made that I don't want to do it.
For now, multiple languages ​​are only available for certain videos.

**Comment by Taapat** [comment]
Check the latest plugin version.
The commit that closes this issue fixes your problem.
Now the plugin should always choose the audio track with the original or default language.

**Comment by QuarkFermion** [comment]
Sorry, didn't notice. Thank you very much.

**Comment by Taapat** [comment]
Are there really that many videos with translations?
If that's the case, then it would be simple to add an option in the plugin settings to select a track with the language set in enigma, if one exists, instead of the default.

**Comment by QuarkFermion** [comment]
Because of this new YouTube feature there will be more and more of these horrible AI translations in the future. But the content creator can disable this feature in it's channel settings. But because it is a new feature, most content creators have no idea.

These AI auto translations are really bad especially for my native language. I watch a lot of IT, dev tutorials and news from the US or UK (English as original). These AI translations to my native language are very bad. 

I am not sure if I understand you correctly. 

It would be nice to have an additional setting to select the preferred audio track language within the plugin. And as you explained, the plugin uses this language if available instead of the default/original. 

But this setting should also provide the setting "default/original" for the default audio track. So that the default/original soundtrack will always be selected by the plugin no matter what additional languages are available. 
I think YouTube calls it "original" audio.

**Comment by QuarkFermion** [comment]
@Taapat 
I have updated the plugin from the OpenATV 7.4 feed. 
Unfortunately it doesn't fully work as intended. It still uses the translation and not the original audio track while playback or as a download. 

Examples, still wrong audio track, not "original":
https://www.youtube.com/watch?v=8scG3KhC6Wo
https://www.youtube.com/watch?v=4C9TH_MoYlY

The downloaded and merged file show "Original" in the track selection screen although it is the translated audio track. 

Another minor issue:
Example, correct "original" track but wrong name:
https://www.youtube.com/watch?v=T5y3L29nOfA

This video works (did not before), playback and download selects the original German audio track correctly but the name in the track selection screen says "English". 

Thanks again.

**Comment by Taapat** [comment]
Is the latest plugin version available on OpenATV 7.4 feed?
Are you using the version after my changes?
The version must be at least git1238.

**Comment by QuarkFermion** [comment]
It was offered for update a couple of hours ago.

enigma2-plugin-extensions-youtube - git1242+f0d2ac70+f0d2ac7bf7-r0

**Comment by Taapat** [comment]
Do you restart enigma after installing the plugin?
I try all your provided links and plugin always chooses the English audio track for me.

**Comment by Taapat** [comment]
I found a problem.
I tried specifying the search language as English or my Latvian. For example, if you specify Italian as the search language in the settings, YouTube gives you the Italian translation as the default.

**Comment by QuarkFermion** [comment]
Thanks for the tip but I always perform a full reboot after updates.

Yes, I can confirm the problem with the search language setting. 

If I set the search language from German to English the videos with the English original audio track work (playback and downloads), examples. It selects the correct audio track (original, English).

I tested this before your changes a week ago because I assumed the search language setting was responsible. With the old version nothing had changed.

But with the original German video the plugin selects the English audio track if I set the search language to English.

There is a little bit of work to do, sorry. ;-) 

Thanks for your investigation.

**Comment by Taapat** [comment]
Try after the last changes.
Now the plugin needs to select language according to the language in the plugin settings.

**Comment by QuarkFermion** [comment]
Cool, I will try these changes and report back as soon as the update arrives in the OpenATV 7.4 feed.

**Comment by QuarkFermion** [comment]
I have got Git1245 moments ago.

Sorry, but I think I have misunderstood your previous description of the solution. I thought there would be an additional audio language setting. 

There is no additional language setting, correct? 
Do you use the the search language?

A separate audio language setting with the possibility to set it also to original audio track would be necessary.

I watch videos with original audio tracks in German and English. 

If I set the language to "German" I will always get the horrible translation with videos that are original English and vice versa. 

It would be necessary to have a separate audio language setting with the additional parameter "original audio". 

If this solution is too complicated to implement it would be better to always select the original audio track for playbacks and downloads, regardless of the search language set or available.

Thank you very much for your patience.

**Comment by Taapat** [comment]
Youtube set default track according to search language.
If there is translation available according to given language then set it as default, if not then original.

I can create if in search language select All or change this entry to Original, then original language will always be selected.
Actually it will be like in version git1238 if search language is English.

**Comment by Taapat** [comment]
I don't see the point in creating a separate audio language setting, because technically it will replace the original search language setting.

**Comment by Taapat** [comment]
In fact, it is the player's interface language: https://developers.google.com/youtube/player_parameters#hl
In this language is displayed all information (descriptions, etc.), but in the plugin it is used only in error messages.
This also affects the default track.
If you select All, then the default ilanguage is English.
So far there were no translated tracks and I did not pay attention to the settings name.

I do not want to change the names of the settings without a serious reason because it affects all translations.
If change it, then I think it would be correct to rename this settings entry to "Interface language" and change "All" to "Original", but the user might not understand the meaning of this either.

**Comment by QuarkFermion** [comment]
Yes, I totally agree.

I had already thought that renaming would lead to problems. It was just an idea, but in the end it makes no sense. 

I tested Git1245 with different search language settings and it works.

So, it would be great if you were able to change the behaviour of the search language set to "All" to the selection of the original audio language instead of English.

Would that be acceptable for you? Thanks.

**Comment by Taapat** [comment]
Try after the last changes.

**Comment by QuarkFermion** [comment]
Git1247

For videos with additional translated audio tracks the "All" setting selects the original audio track for playbacks and downloads.

Unfortunately, it seems if there is only one audio track (the original) the plugin does not select this track. There is no audio during playback or in downloads in this case. 

Minor problem:
For my German example video with translated tracks with "All" setting the original German audio track gets the wrong name "English" in the downloaded file. In English videos this works and the name is "Original". But maybe a problem with the German video.

**Comment by QuarkFermion** [comment]
> Unfortunately, it seems if there is only one audio track (the original) the plugin does not select this track. There is no audio during playback or in downloads in this case.

Sorry, I forgot to mention that this happens with "All" as search language setting.

**Comment by Taapat** [comment]
Try again after the last changes.
I radically changed the ulr fetching logic and this should eliminate the possibility of not getting the audio track.

**Comment by QuarkFermion** [comment]
Great work!
I have tested the combinations of search languages (All, German, English) single-track videos and multi-track videos for downloads and playback. Everything works perfectly. 

The problem mentioned with the incorrectly named audio track after the download seems to be a problem with my sample video itself.

Thank you very much again. Merry Christmas!
