### ISSUE TITLE
Some videos are not playing

### ISSUE THREAD

**Issue by hulinov** [Taapat/enigma2-plugin-youtube#26]
Some videos are not playing from new ""enigma2-plugin-youtube-master.zip""
This video does not pass: https://www.youtube.com/watch?v=qtu0XFU8AvU

**Comment by Taapat** [comment]
What is your receiver and image?
Do you use the latest plugin version?
Did you try to close the plugin and after try again?

For me on vuplus solo2 with openpli-6.0 develop image this video works.

**Comment by hulinov** [comment]
[enigma2-plugin-extensions-youtube_1.r7_all.deb.zip](https://github.com/Taapat/enigma2-plugin-youtube/files/1191440/enigma2-plugin-extensions-youtube_1.r7_all.deb.zip)
Image Unstable for DM900UHD,
I want to start playing video and it will not run without error.

**Comment by hulinov** [comment]
I'm sorry insert enigma2log 
[enigma2.log.zip](https://github.com/Taapat/enigma2-plugin-youtube/files/1191521/enigma2.log.zip)
Gstreamer error:...  :-(

**Comment by Taapat** [comment]
It looks like that.
So I'll close this issue.

**Comment by hulinov** [comment]
I'm sorry and thank you.You could implement youtube into deb version?

**Comment by Taapat** [comment]
Sorry, but I build packages on openpli-oe-core where the packages are in ipk format.

I'm surprised that the plugin works on the new DM images.
I have the impression that they are much different and many features from old enigma2 do not work.

**Comment by hulinov** [comment]
I understand, otherwise, a great plugin. :-)

**Comment by hulinov** [comment]
I'm sorry,but If you change the setting in Maximum videoresolution:640x360,so the video plays.

**Comment by Taapat** [comment]
I'm sorry.
I check your log the second time.

You need to pay attention to your image developer on this commit: https://github.com/Taapat/enigma2-plugin-youtube/commit/58f447dfecbc6ff86da8896113888201b5adaf5e

I point in this commit what changes need to make in the enigma if you want to use the new feature to play Dash MP4 video: https://github.com/OpenPLi/enigma2/commit/65962a39625aaf02f66ee9258181ec2d164916a6

If he does not make this changes in the enigma then he needs to freeze plugin version in the feed on version before this changes.

**Comment by hulinov** [comment]
Thank you,very help me.I'm from slovakia :-).In the file YoutubeVideoUrl.py  
""""                     
 from swfinterp import SWFInterpreter


PRIORITY_VIDEO_FORMAT = []


def createPriorityFormats():
	global PRIORITY_VIDEO_FORMAT
	PRIORITY_VIDEO_FORMAT = []
	use_format = False
	for itag_value in ['38', '37', '96', '22', '95', '120',
		'35', '94', '18', '93', '5', '92', '132', '17']:
		if itag_value == config.plugins.YouTube.maxResolution.value:
			use_format = True
		if use_format:
			PRIORITY_VIDEO_FORMAT.append(itag_value)

createPriorityFormats()

DASHMP4_FORMAT = [
 		'133', '134', '135', '136', '137', '138',
 		'160', '264', '266', '298', '299'
 	]

IGNORE_VIDEO_FORMAT = [
		'43',  # webm
		'44',  # webm
		'45',  # webm
		'46',  # webm
		'100',  # webm
		'101',  # webm
		'102'  # webm
	]


def uppercase_escape(s): """""
Playing format 1280x720p,480x360p....
Thank you very much.

**Comment by hulinov** [comment]
Excuse me that I'm annoying again,but playing trough search videos forexample: [](url)https://www.youtube.com/watch?v=YqeW9_5kURI     writes an error:""" KeyError: 'videoId' """
It's also in ipk version?

**Comment by Taapat** [comment]
What exactly do I need to do in the plugin to get this error?

**Comment by hulinov** [comment]
Try to follow pictures in order -->
![youtube](https://user-images.githubusercontent.com/30618343/28976192-3ba2a032-793d-11e7-8738-b0b193c0f9e3.png)
![youtube1](https://user-images.githubusercontent.com/30618343/28976225-611feedc-793d-11e7-8141-eaeba91e4cd3.png)
![youtube2](https://user-images.githubusercontent.com/30618343/28976231-682fa5c8-793d-11e7-8847-5c0d5754003f.png)
![youtube3](https://user-images.githubusercontent.com/30618343/28976239-70040384-793d-11e7-8062-bfef14f11d41.png)

**Comment by Taapat** [comment]
And where is problem?
![screenshot1](https://user-images.githubusercontent.com/1623947/28979563-f975ce6c-7952-11e7-9b7d-a2fd39f61f8e.jpg)
![screenshot2](https://user-images.githubusercontent.com/1623947/28979567-fbb44258-7952-11e7-979a-603a1c605d14.jpg)
![screenshot3](https://user-images.githubusercontent.com/1623947/28979572-feed14f4-7952-11e7-9d8a-d7c50bcbd623.jpg)

**Comment by hulinov** [comment]
Help editing in YouTebeUi.py(for deb version):
before	920	for result in searchResponse.get('items', []):
		921		videos.append(result['id']['videoId'])
		922	return self.extractVideoIdList(videos)

then         920  for result in searchResponse.get('items', []):
		921		try:
	921	922		    videos.append(result['id']['videoId'])
		923	        except:
		924		    pass
	922	925	return self.extractVideoIdList(videos)
![youtube](https://user-images.githubusercontent.com/30618343/28996089-e9389588-79f8-11e7-9a53-9f5c2a13e2d5.jpg)
Thank you,:-)

**Comment by Taapat** [comment]
I do not create any deb package.
I do not know who they are created, and what version of the plugin is used in them.
Maybe your package does not have the latest plugin version.
