### ISSUE TITLE
There was an error in extract video url

### ISSUE THREAD

**Issue by willow5** [Taapat/enigma2-plugin-youtube#263]
Hello Taapat and thank you for everything you are doing for this community. I have downloaded the latest file and some videos are playing well but others come up with this error. Can you kindly investigate? Thank you
![1_0_1_20B0_808_2_11A0000_0_0_0_20241221223851](https://github.com/user-attachments/assets/c4ab4800-261f-40ed-8762-689ba2e62234)

**Comment by Taapat** [comment]
Please post the enigma2 debug log when this happens.

**Comment by willow5** [comment]
Thank you Taapat! How do I do that please?

**Comment by Taapat** [comment]
Asked in your image support forum how to get enigma2 debug log .

**Comment by willow5** [comment]
Does this give you enough information ?

`14:00:49.8358 [YouTubeVideoUrl] Try fmt url
14:00:49.8360 [YouTubeVideoUrl] Try manifest url
14:00:49.8361 [YouTube] Error in extract info: Please sign in
14:00:49.8388 [Skin] Processing screen 'MessageBox' position=(240,160), size=(800,400) for module 'MessageBox'.
14:00:49.8518 [MessageBox] Timeout set to 8 seconds.
14:00:49.8542 [Skin] Processing screen 'MessageBoxSummary', from list 'MessageBoxSummary, MessageBox_summary, ScreenSummary', position=(0,0), size=(400,240) for module 'MessageBoxSummary'.
14:00:49.8569 [eRCDeviceInputDev] 0 160 1
14:00:49.8571 [InfoBarGenerics] Key 'KEY_OK' (352) Break.
14:00:57.8805 [MessageBox] Timeout!
14:00:59.4400 [eRCDeviceInputDev] 1 160 1
14:00:59.4403 [InfoBarGenerics] Key 'KEY_OK' (352) Make.
14:00:59.4404 [ActionMap] Map screen 'N/A' context 'WizardActions' -> Action 'ok'.
14:00:59.4405 [YouTube] Selected: eIrlNivgG_U
14:00:59.6939 [YouTubeVideoUrl] Age gate content
14:01:00.0382 [YouTubeVideoUrl] Try fmt url
14:01:00.0384 [YouTubeVideoUrl] Try manifest url
14:01:00.0385 [YouTube] Error in extract info: Please sign in
14:01:00.0412 [Skin] Processing screen 'MessageBox' position=(240,160), size=(800,400) for module 'MessageBox'.
14:01:00.0526 [MessageBox] Timeout set to 8 seconds.
14:01:00.0539 [Skin] Processing screen 'MessageBoxSummary', from list 'MessageBoxSummary, MessageBox_summary, ScreenSummary', position=(0,0), size=(400,240) for module 'MessageBoxSummary'.
14:01:00.0572 [eRCDeviceInputDev] 0 160 1
14:01:00.0575 [InfoBarGenerics] Key 'KEY_OK' (352) Break.`

**Comment by Taapat** [comment]
This is age gate content.
As written in the error message- please sign in.
In plugin settings enable Login on startup, perform plugin authentication and you will be able to watch some age gate content.
There may still be problems with some but this video works for me.

**Comment by willow5** [comment]
Understood, sorry for the user error this time! Thanks Taapat

**Comment by Taapat** [comment]
Try the latest version of the plugin.
I added the ability to play some (not all) age gated videos without authorization.

**Comment by willow5** [comment]
Thx for trying. The same error but I know what I need to do
