### ISSUE TITLE
Crash when searching for Media Open BlackHole 1.0

### ISSUE THREAD

**Issue by nunigaia** [Taapat/enigma2-plugin-youtube#27]
Hi

During some tests, when trying to search for Videos, i got crashlog´s:

Stb Model: Vuplus Ultimo4k
Image: Open BlackHole 1.0

`<   427.630> [ActionMap] unknown action SetupActions/6! typo in keymap?
<   427.754> [eInputDeviceInit] 0 7 1
<   427.754> [InfoBarGenerics] KEY: 7 6
<   428.458> [eDVBServicePlay] timeshift
<   428.458> [eDVBServicePlay] timeshift
<   428.986> [eInputDeviceInit] 1 160 1
<   428.987> [InfoBarGenerics] KEY: 352 OK
<   428.988> [ActionMap] SetupActions ok
<   428.988> [YouTube] Search: tiesto
<   429.469> Traceback (most recent call last):
<   429.469>   File "/usr/lib/enigma2/python/Plugins/Extensions/YouTube/YouTubeUi.py", line 510, in splitTaimerStop
<   429.469>   File "/usr/lib/enigma2/python/Plugins/Extensions/YouTube/YouTubeUi.py", line 929, in createEntryList
<   429.469> KeyError: 'videoId'
<   429.469> [ePyObject] (CallObject(<bound method YouTubeMain.splitTaimerStop of <class 'Plugins.Extensions.YouTube.YouTubeUi.YouTubeMain'>>,()) failed)`

Can you please try or help how to fix this issue, thanks.

best regards
nunigaia

**Comment by Taapat** [comment]
1. Do you use the latest plugin version?
2. What and where exactly you are search when get this error?
I have never seen such an error.

**Comment by nunigaia** [comment]
Sorry, i forget this mention. Yes ... enigma2-plugin-extensions-youtube_h1+git346+2ac3936-r0.0_all.ipk
