### ISSUE TITLE
Some crashes from latest released binary

### ISSUE THREAD

**Issue by Ntemis** [Taapat/enigma2-plugin-youtube#29]
[enigma2_crash_1514386520.log](https://github.com/Taapat/enigma2-plugin-youtube/files/1591912/enigma2_crash_1514386520.log)
[enigma2_crash_1514269903.log](https://github.com/Taapat/enigma2-plugin-youtube/files/1591913/enigma2_crash_1514269903.log)
[enigma2_crash_1514019264.log](https://github.com/Taapat/enigma2-plugin-youtube/files/1591915/enigma2_crash_1514019264.log)

**Comment by Taapat** [comment]
Thank you for the report.

Only in the first crash log I see a threading error caused by my plugin.
How do you get this error? It looks like it's some kind of threading issue in your image.

The other crash logs does not contain any error indicated on my plugin. Why did you add them here?

**Comment by Ntemis** [comment]
I just had them all in the log folder and i presume its all related, sorry for that,and also can you please release a new ipk package as i dont have a bitbake env available to test the greek support :)

**Comment by Ntemis** [comment]
Forgot to tell you how i get this error:
I tried to search with an empty line

**Comment by Taapat** [comment]
I upload an updated ipk.

Can you write more in detail, step by step, exactly what you do before you get gsod?
On the openpli image I can not get such a crash with an empty search line.

**Comment by Ntemis** [comment]
Happened again while i was trying to search with greek codepage keyboard

**Comment by Taapat** [comment]
What exactly you do not understand in this sentence:
> Can you write more in detail, step by step, exactly what you do before you get gsod?
