### ISSUE TITLE
Download over 1920x1080 no audio

### ISSUE THREAD

**Issue by vatlach** [Taapat/enigma2-plugin-youtube#31]
When download any video from youtube downloaded without audio.Under 1920x1080 resolution downloaded with audio.Very strange....

**Comment by Taapat** [comment]
On 1920x1080 resolution is used DASH MP4 streams.
One stream for video, the other for audio.
The enigma tuner can not play these two streams from the hdd together. I introduced this option only for network streams.
So I chose to download only a DASH MP4 video: https://github.com/Taapat/enigma2-plugin-youtube/commit/3fb2eac6de0b3984bf12f7bc16cede432958fc1c

If later I myself, or someone else will introduce the ability to play both files together, then I can introduce both files (video and audio) download.

**Comment by vatlach** [comment]
Can you download video and audio to HDD and after merge with gstreamer to one file.Possible do this?
