### ISSUE TITLE
#Crashing frequently at searching input,tested on more type of VU+ Receiver...Please if possible add google search suggestion settings on/off possibility!

### ISSUE THREAD

**Issue by S4iyan3lit3** [Taapat/enigma2-plugin-youtube#35]
!!!!!!!!!!!!!!!!!!!! PARTIAL SOLUTION WHICH FIXED THE ISSUE IS => REMOVING THE FOLLOWED LINES FROM "YouTubeSearch.py" => "LINE 333 to 360" !!!!!!!!!!!!!!!!!!!!!!!!!!!!!

.............small cut from full log file........

(Enigma2)
VTi 9.0.1 
Kernel 3.13.5

header: Accept-Ranges: none

header: Vary: Accept-Encoding

header: Transfer-Encoding: chunked

Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/YouTube/YouTubeSearch.py", line 276, in finished
    message[1](message[0])
  File "/usr/lib/enigma2/python/Plugins/Extensions/YouTube/YouTubeSearch.py", line 305, in propagateSuggestions
    self.updateSuggestions(suggestions)
  File "/usr/lib/enigma2/python/Plugins/Extensions/YouTube/YouTubeSearch.py", line 41, in updateSuggestions
    self['header'].setText(', '.join(x[0] for x in suggestions[1:]))
KeyError: 'header'
(PyObject_CallObject(<bound method SuggestionsQueryThread.finished of <SuggestionsQueryThread(Thread-5, stopped 1616520336)>>,(0,)) failed)
]]>
		</ ~dvbapp2crashlog>
	</ ~crashlogs>
</ ~stbcrashlog>

**Comment by Taapat** [comment]
From which country do you come?
I have seen a similar crash from the countries that have been affected by Russia's attempts to block the telegram.
Does youtube work without problems in your web browser?

I have not able to get such a crash.
Of course, I can try blindly add an extra try:, but if I do not check it, it may not give the expected result.

**Comment by Taapat** [comment]
Please reopen this issue if my fix not working.
