### ISSUE TITLE
All videos are 640x360, YouTube settings ignored

### ISSUE THREAD

**Issue by kalehrl** [Taapat/enigma2-plugin-youtube#42]
All videos are played at 640x360 resolution.
'Maximum video resolution' in 'YouTube setup' is no longer working.
I have 1280x720 there but it is no longer working.
It worked just fine in the past.
I tried other resolutions but no change.
The same videos can be played in HD resolutions via browser on PC.

**Comment by Taapat** [comment]
Or this really happening with absolutely all videos?
It's strange that nobody else has reported this.
I will check.

**Comment by kalehrl** [comment]
Yes. All videos.

**Comment by nunigaia** [comment]
If i play a video and set the resolution to 1920x1080 or 3840x2160 the sound will go off, if if rew of ff  ( skip back or skip forward ).

Although, i noticed, that after git369 commit, there´s no more spinning around and around until it founds a source playable, i.e., it plays all sources. 

thanks

**Comment by Taapat** [comment]
@nunigaia https://github.com/Taapat/enigma2-plugin-youtube/issues/30

**Comment by Taapat** [comment]
I can not confirm this:
If I set the resolution 640x360 I got:
![640x360](https://user-images.githubusercontent.com/1623947/46087232-8be23f80-c1b2-11e8-8f9f-3c6a21058a34.jpg)

If I set the resolution 1280x720 I got:
![1280x720](https://user-images.githubusercontent.com/1623947/46087244-90a6f380-c1b2-11e8-861c-7c4acf348998.jpg)

Try exit and start plugin again after the resolution change in plugin settings.

**Comment by kalehrl** [comment]
I tried this same video and got 1280x720 as expected because I set that resolution in the plugin.
However, these videos always play at 640x360 even though higher resolutions are available:
https://www.youtube.com/watch?v=O_6G52gjeOU&t=36s&index=2&list=FLlY3S5Ilse3gxJ7yXoNYmdQ
https://www.youtube.com/watch?v=qoxXmuiQobw&list=FLlY3S5Ilse3gxJ7yXoNYmdQ&index=5
and many others.

**Comment by Taapat** [comment]
I assume that they do not have a link with the enigma player understandable format with the highest resolution.
Not all formats that you can see on a PC can be played by the enigma player.

I will check your links later, maybe there is some format that I can add for the enigma player.

**Comment by kalehrl** [comment]
I played these file before at 1280x720 with your plugin.
I don't know what has changed for them to stop playing at that resolution but I doubt YouTube removed some links.

**Comment by Taapat** [comment]
The following formats are available for your first clip:
```
[YouTube] Selected: O_6G52gjeOU
18 {'vcodec': 'h264', 'abr': 96, 'height': 360, 'width': 640, 'ext': 'mp4', 'acodec': 'aac'} 
36 {'width': 320, 'ext': '3gp', 'vcodec': 'mp4v', 'acodec': 'aac'} 
17 {'vcodec': 'mp4v', 'abr': 24, 'height': 144, 'width': 176, 'ext': '3gp', 'acodec': 'aac'} 
137 {'ext': 'mp4', 'format_note': 'DASH video', 'vcodec': 'h264', 'height': 1080} 
248 {'ext': 'webm', 'format_note': 'DASH video', 'vcodec': 'vp9', 'height': 1080} 
136 {'ext': 'mp4', 'format_note': 'DASH video', 'vcodec': 'h264', 'height': 720} 
247 {'ext': 'webm', 'format_note': 'DASH video', 'vcodec': 'vp9', 'height': 720} 
135 {'ext': 'mp4', 'format_note': 'DASH video', 'vcodec': 'h264', 'height': 480} 
244 {'ext': 'webm', 'format_note': 'DASH video', 'vcodec': 'vp9', 'height': 480} 
134 {'ext': 'mp4', 'format_note': 'DASH video', 'vcodec': 'h264', 'height': 360} 
243 {'ext': 'webm', 'format_note': 'DASH video', 'vcodec': 'vp9', 'height': 360} 
133 {'ext': 'mp4', 'format_note': 'DASH video', 'vcodec': 'h264', 'height': 240} 
242 {'ext': 'webm', 'format_note': 'DASH video', 'vcodec': 'vp9', 'height': 240} 
160 {'ext': 'mp4', 'format_note': 'DASH video', 'vcodec': 'h264', 'height': 144} 
278 {'ext': 'webm', 'format_note': 'DASH video', 'container': 'webm', 'vcodec': 'vp9', 'height': 144} 
140 {'ext': 'm4a', 'format_note': 'DASH audio', 'container': 'm4a_dash', 'abr': 128, 'acodec': 'aac'} 
171 {'ext': 'webm', 'format_note': 'DASH audio', 'abr': 128, 'acodec': 'vorbis'} 
249 {'ext': 'webm', 'format_note': 'DASH audio', 'abr': 50, 'acodec': 'opus'} 
250 {'ext': 'webm', 'format_note': 'DASH audio', 'abr': 70, 'acodec': 'opus'} 
251 {'ext': 'webm', 'format_note': 'DASH audio', 'abr': 160, 'acodec': 'opus'} 
```
As you can see, the mp4 video is only with a resolution of 360x640.
Until now, youtube used DASH video only for HD and higher resolution, thefore DASH video is available in resolution starting from 1920x1080. For the resolution up to 1280x720, a mp4 video was always available.
There are no mp4 videos with higer resolution in your clips mentioned above.
You can set in configs resolutin to 1920x1080 and you will have DASH video video with that resolution.

What image do you use?
I do not know whether there is still a active images that does not support paralel playback of two, video and audio streams.
Maybe I'll add DASH video also for lower resolution.
I see no reason to implement a separate config for DASH video if none of other formats are available.

**Comment by kalehrl** [comment]
I use openpli 6.2
I just tried setting the resolution to 1920x1080 and the video doesn't play at all.
The player just starts playing the second video.
Other videos in my post are also skipped.

**Comment by kalehrl** [comment]
It doesn't work when using ServiceApp and exteplayer3 or gstplayer.
When I switched to default enigma2 player and 1920x1080 resolution in the plugin, the video played fine at 1920x1080 resolution. I guess there is a bug in exteplayer3 and gstplayer.

**Comment by Taapat** [comment]
There are no bugs in exteplayer3 or gstplayer.
In they simply are not implemented two stream playback using  'suburi=' in link, which I created for servicemp3 in enigma.

**Comment by kalehrl** [comment]
Thank you for your help.
From now on I will use the default enigma2 player for YouTube and for others ServiceApp.
It requires an enigma2 restart but I can live with that.

**Comment by Taapat** [comment]
After this https://github.com/mx3L/serviceapp/commit/f5becf8f5f4c78bb43c8c0eb0f937f9c4be8ddf9 exteplayer3 should play DASH streams from my plugin.

**Comment by antoniovalenzuela** [comment]
Hi @Taapat

I have OpenPli, how can solve this issue to play HD videos? serviceapp exteplayer3.

**Comment by Taapat** [comment]
Or you use original OpenPLi 7.0 image?
On OpenPLi 7.0 with latest updates should work resolution higer that 640x360.

**Comment by antoniovalenzuela** [comment]
box DM900 latest openpli v6.2

**Comment by antoniovalenzuela** [comment]
i found "OpenPLi 7* by Japhar Team, December 13th 2018"

**Comment by Taapat** [comment]
Also on latest OpenPLi 6.2 should work resolution higer that 640x360.
Or you try plugin from feed or latest from download: http://taapat.ho.ua/enigma2-plugin-youtube/

**Comment by Taapat** [comment]
If you want to use exactly serviceapp you need latest serviceapp version with my changes on your image feed.
Ask your image builders.

**Comment by antoniovalenzuela** [comment]
Months ago I could watch HD with version 6.2. Now install OpenPli 7 and the same thing happens.

Plugin enigma2-plugin-extensions-youtube_h1 + git395 + 8027203-r0.0_all.ipk

Settings YouTuve 640x360 plays all the videos.

1080P deco resolution. IP TV streamings load perfect.

Can you get a log to help me?

**Comment by Taapat** [comment]
Maybe first give an example what clip you don't have in HD.

**Comment by antoniovalenzuela** [comment]
any latest hits 720 or 1080. Play and return to youtube menu.

https://www.youtube.com/watch?v=UdITqp3EmHI

**Comment by Taapat** [comment]
On gigablue UE 4K using opnepli develop image I don't have problem not with gstreamer using servicempr3 not with ffmpeg using serviceapp and exteplayer3:
![screenshot](https://user-images.githubusercontent.com/1623947/52911755-fce4d980-32b0-11e9-819c-c456845ebce6.jpg)

Maybe you can give enigma2 log.

**Comment by antoniovalenzuela** [comment]
I found information that could help, enigma2 debugging.

URL video 640 -->

https://r2---sn-8ug-njay.googlevideo.com/videoplayback?id=o-AOPXB3VsUYbwt5eCD7hi-Tu_SjDYmd4GYtgNRzmjEDWR&ei=OWVpXJWHDdeuxATu866wAg&initcwndbps=1601250&fvip=3&lmt=1541916497078640&ip=190.161.150.71&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&gir=yes&dur=339.731&expire=1550432665&pl=24&ratebypass=yes&pcm2cms=yes&mime=video%2Fmp4&itag=18&c=WEB&ipbits=0&ms=au%2Crdu&mt=1550410953&mv=m&source=youtube&clen=9108268&requiressl=yes&key=yt6&txp=5531432&mm=31%2C29&mn=sn-8ug-njay%2Csn-8ug-njae&signature=177823556E460E1811161B80E4718165580AEE3B.4DF8456A1785142279A47DDA52DDD464BA6E0933

Enigma plugin and chrome browser play Ok!


URL video 1080 -->

https://r3---sn-8ug-njael.googlevideo.com/videoplayback?expire=1550432403&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&key=yt6&c=WEB&gir=yes&id=o-AJIyvu7Kshut94slMulcTNqxs8tLChU4yqaxVSRwzccZ&mm=31%2C29&mn=sn-8ug-njael%2Csn-8ug-njae&dur=2202.099&pl=24&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398&ip=190.161.150.71&lmt=1544417234124922&ei=M2RpXKT3EcaBwATKiKy4Bw&keepalive=yes&ms=au%2Crdu&source=youtube&mv=m&clen=146648647&requiressl=yes&ipbits=0&mime=video%2Fmp4&initcwndbps=1625000&mt=1550410670&itag=136&txp=5535432&fvip=7&signature=4B13BCDAFCB840C642BEA9082537C73900C2C51E.887D6CF5073DFA057998B37F0C960700F3695060&ratebypass=yes&suburi=https://r3---sn-8ug-njael.googlevideo.com/videoplayback?expire=1550432403&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&key=yt6&c=WEB&gir=yes&id=o-AJIyvu7Kshut94slMulcTNqxs8tLChU4yqaxVSRwzccZ&mm=31%2C29&mn=sn-8ug-njael%2Csn-8ug-njae&dur=2202.551&pl=24&ip=190.161.150.71&lmt=1544375837626268&ei=M2RpXKT3EcaBwATKiKy4Bw&keepalive=yes&ms=au%2Crdu&source=youtube&mv=m&clen=35646580&requiressl=yes&ipbits=0&mime=audio%2Fmp4&initcwndbps=1625000&mt=1550410670&itag=140&txp=5533432&fvip=7&signature=DA45F593E02B490DBC21B4F618527BE4B2BA9127.39CCEA40462EBDD88B973A82DC49E5F27FFE6C1B

Enigma plugin back to menu and chrome browser "Access was denied to r2---sn-8ug-njay.googlevideo.com.  You do not have authorization to view this page"

In 1080 are 2 URLs. Video + Audio
If I cut each URL I can see and listen (separately)

Direct access https://www.youtube.com/watch?v=8TdeNbKeXAw&t=10s 
I can see, that's ok

Why will deny access occur?

**Comment by Taapat** [comment]
This is because in your image is not used this change: https://github.com/OpenPLi/enigma2/commit/65962a39625aaf02f66ee9258181ec2d164916a6
But it should by in OpenPLi 6.2.
I can conclude that on drembox it doesn't work.

**Comment by antoniovalenzuela** [comment]
Then I can not do anything to play high resolutions?

**Comment by Taapat** [comment]
Or on your image feed is not available latest plugin serviceapp?

**Comment by antoniovalenzuela** [comment]
latest it's installed by default

Package enigma2-plugin-systemplugins-serviceapp (1+git141+9086558-r2) installed in root is up to date

**Comment by Taapat** [comment]
This is not latest verion of serviceapp.  This version is from 23 Apr 2018. You need latest versinon from 12 Nov 2018 on branch develop.

**Comment by antoniovalenzuela** [comment]
thanks, I'll see how to update.

Install the ServiceApp IPK from an OpenPli 7 repository, it did not work.

**Comment by Taapat** [comment]
You cannot install this plugin from other images.
Maybe only if another image build system and enigma are identical.
Therefore, you need to ask your image builder update plugin on feed.

**Comment by antoniovalenzuela** [comment]
i decided change image to Pure2 
http://pur-e2.club/OU/images/index.php?dir=6.2/dreambox/&file=dm900-PurE2-6.2-20190217.rootfs.tar.bz2

Better than OpenPli, and with updates up to date =)

IPTV Bouquets and Youtube (HD) working

**Comment by Taapat** [comment]
You are very mistaken!
OpenPLi does not support DM900: https://openpli.org/download/dreambox/
Any image that includes OpenPLi in its name is not an OpenPLi image but just **based on OpenPLi**.
And as you see it is a very big difference, because it depends on the knowledge of the image makers.

**Comment by antoniovalenzuela** [comment]
If I know that it is a version based on OpenPli, with the same name for DM900 http://www.pli-images.net

It works fine, but the only exception for months is that I can not watch YouTube HD. And the last update was in jun 2018.

For my deco there are many base images and others created by teams using these bases.

With PurE2 I'm fine, I only watch streamings  ;)
