### ISSUE TITLE
why i can't play this video Dj khaled No brainer officiel  video in my pc work but  with your  youtube plugin not work

### ISSUE THREAD

**Issue by vuteam** [Taapat/enigma2-plugin-youtube#46]

**Comment by koivo** [comment]
There is missing a button "Bullshit allowed" inside youtube options :D

**Comment by Taapat** [comment]
Do you write about this video?
![screenshot](https://user-images.githubusercontent.com/1623947/48864847-867e2b80-edd6-11e8-8fec-cabdb00014be.jpg)

What is your receiver and image?

**Comment by vuteam** [comment]
Ok Thank you sir
