### ISSUE TITLE
OpenATV 5.1 is not opening FullHD youtube videos

### ISSUE THREAD

**Issue by Butvo** [Taapat/enigma2-plugin-youtube#49]
Hello Taapat,
Could you please help, with last install youtube plugin h1+git377+2dd4fd, I can not open youtube videos. Looks it is related to the FullHD Videos reslution1920x1080.
I can play some videos but not with FullHD, in my problem it is searching and looks opening video fine, but then it is stoping and no progress of play.
I have dm800sev2 with OpenATV 5.1 / Enigma 2

Can it be codec problem or? I tried change resolution to 720p but still same problem.

Installed>
m800sev2:~# ipkg list_installed |grep python
libpython2.7-1.0 - 2.7.9-r1
python-argparse - 2.7.9-r1
python-audio - 2.7.9-r1
python-cheetah - 2.4.4-r3
python-codecs - 2.7.9-r1
python-compression - 2.7.9-r1
python-contextlib - 2.7.9-r1
python-core - 2.7.9-r1
python-crypt - 2.7.9-r1
python-ctypes - 2.7.9-r1
python-datetime - 2.7.9-r1
python-difflib - 2.7.9-r1
python-elementtree - 2.7.9-r1
python-email - 2.7.9-r1
python-fcntl - 2.7.9-r1
python-html - 2.7.9-r1
python-image - 2.7.9-r1
python-imaging - 1.1.7-r5
python-io - 2.7.9-r1
python-json - 2.7.9-r1
python-lang - 2.7.9-r1
python-logging - 2.7.9-r1
python-math - 2.7.9-r1
python-mime - 2.7.9-r1
python-misc - 2.7.9-r1
python-netclient - 2.7.9-r1
python-netserver - 2.7.9-r1
python-numbers - 2.7.9-r1
python-pickle - 2.7.9-r1
python-pprint - 2.7.9-r1
python-process - 1.0-r7
python-pyopenssl - 0.13.1-r3
python-pyusb - 1.0.0a2-r1
python-re - 2.7.9-r1
python-readline - 2.7.9-r1
python-shell - 2.7.9-r1
python-stringold - 2.7.9-r1
python-subprocess - 2.7.9-r1
python-textutils - 2.7.9-r1
python-threading - 2.7.9-r1
python-twisted-core - 13.2.0-r0
python-twisted-protocols - 13.2.0-r0
python-twisted-web - 13.2.0-r0
python-unixadmin - 2.7.9-r1
python-utf8-hack - 0.2-r2
python-wifi - 0.5.0-r2
python-xml - 2.7.9-r1
python-zlib - 2.7.9-r1
python-zopeinterface - 4.1.1-r0

dm800sev2:~# ipkg list_installed |grep yout
enigma2-plugin-extensions-youtube - h1+git377+2dd4fd7-r0.0
dm800sev2:~# 

dm800sev2:~# ipkg list_installed |grep ff
ffmpeg-x264-presets - 9.18-r0
libffi6 - 3.2.1-r0
libgstriff-1.0-0 - 1.5.1-r0
mtd-utils-jffs2 - 1.5.1+git0+9f107132a6-r0
python-difflib - 2.7.9-r1
dm800sev2:~#

**Comment by Taapat** [comment]
Hi,
Youtube actively switch to dash format, which has a separate stream for video and a separate for audio.
I've created a workoraund in enigma to play both of these streams, but it's still a hack: https://github.com/OpenPLi/enigma2/commit/65962a39625aaf02f66ee9258181ec2d164916a6
Therefore, it is possible that on all receivers this do not work as expected.

I have report that dreambox with unofficial OpenPL image also have problems with dash playback.
I guess there are specific problem in dvbmediasink on dreamboxes.
If on feed you have the latest serviceapp with my fix: https://github.com/mx3L/serviceapp/commit/f5becf8f5f4c78bb43c8c0eb0f937f9c4be8ddf9
you can try to use the serviceapp for playback. With serviceapp dash is played without problems.
But I do not know if on OpenATV 5.1 is used latest serviceapp.
Perhaps you need to try a latest OpenATV image version.

**Comment by Butvo** [comment]
Hello Taapat,

I have been installed OpenAtv version 6.2 and YouTube  git377 is working fine there with Full HD resolution. Perfect news!

Thank you for your help
We can close this
Butvo
