### ISSUE TITLE
there is a problem about search live broadcasts

### ISSUE THREAD

**Issue by suatsuphi** [Taapat/enigma2-plugin-youtube#54]
Hi,
thank you for this plugin... 
there is a problem with search live broadcasts - there is no result... 
when it was working, there was the other problem with live broadcasts. 
If you don't start it when it is started (live broadcasts), you cant watch the live broadcast - you have to watch from the beginning

thank you

**Comment by Taapat** [comment]
Hi,
Could you write what you are searching in live broadcasts.
I often don't use live broadcasts and what I check for the test is working for me.
