### ISSUE TITLE
token problem !

### ISSUE THREAD

**Issue by thawtes** [Taapat/enigma2-plugin-youtube#55]
hi, @Taapat 

some times the video will not open!
e2 log :  [YouTubeVideoUrl] "token" parameter not in video info for unknown reason

Can you check it?

**Comment by Taapat** [comment]
If this fix not help, please give link example where you get this error.

**Comment by thawtes** [comment]
> 
> 
> If this fix not help, please give link to example where you get this error.

thank you dear @Taapat, now is working...

**Comment by kalehrl** [comment]
Could you please compile the latest version of your plugin and upload it to your downloads section?
