### ISSUE TITLE
Download Size info

### ISSUE THREAD

**Issue by ozone1864** [Taapat/enigma2-plugin-youtube#58]
Dear Taapat,
First of all thank you for this superb plugin. If you can add download size popup before we attempt to download the video since when we download a video, the active downloads tab shows us percentage and not the total size in MB or GB of the download.
Best Regards,

**Comment by Taapat** [comment]
Hi,
Or you want to get a file size warning before downloading or see the download file size when download?

**Comment by ozone1864** [comment]
> Hi,
> Or you want to get a file size warning before downloading or see the download file size when download?

Yes please thank you

**Comment by ozone1864** [comment]
Any news @Taapat

**Comment by Taapat** [comment]
Sorry, I'm busy with other things.
I will try to find the time to think about the solution.
