### ISSUE TITLE
Watch later section is missing

### ISSUE THREAD

**Issue by ozone1864** [Taapat/enigma2-plugin-youtube#59]
Hello,
In youtube account you got watch later and playlist sections,
when you sign in  using the plugin to youtube it only shows playlist 
Can you add watch later section ?
Regards,

**Comment by Taapat** [comment]
Hi,
Unfortunately youtube in september 15, 2016 removed watch history and watch later from API.
https://developers.google.com/youtube/v3/revision_history#september-15-2016
> Thus, the watch history and watch later playlist IDs cannot be retrieved via the API.

**Comment by ozone1864** [comment]
Ah ok thank you @Taapat  !
