### ISSUE TITLE
Error when trying to show Newest Vids of My Subscriptions

### ISSUE THREAD

**Issue by dede1988188** [Taapat/enigma2-plugin-youtube#63]
Hi,

I use OpenATV 6.3. When I want to see a list of new vids of my Subscriptions it shows "error while creating the list. Please try again later". I tried it many times. I also tried the same thing on OpenPLI 7.1. Its just the same there. Did you heard of that problem already?

**Comment by dede1988188** [comment]
Ive changed the youtubeui.py, but the plugin now loads only 24 vids when i click on newest vids. And these 24 arent the newest vids. They are in fact several days old. Is it supposed to work that way?

**Comment by Taapat** [comment]
Technically, should take the last 8 entries from all of your subscriptions, sort them by date and display as many as you have set in Search results.
