### ISSUE TITLE
Error in creating entry list

### ISSUE THREAD

**Issue by toni185** [Taapat/enigma2-plugin-youtube#67]
Not working from today. Tried downloading latest version and the same thing happening. Can't open any list or video. Please check 🙏

**Comment by toni185** [comment]
Working today again! Great

**Comment by Taapat** [comment]
Thanks for the report!

I think the problem was that I had the plugin OAuth quota so far 1,250,000 uses per day, but the uses exceed that.
I asked youtube to increase it and they did it today.

**Comment by toni185** [comment]
Thanks for fixing it was working great. But now again same problem on my receiver. Please check 🙏

**Comment by kalehrl** [comment]
This morning the same error.

**Comment by Taapat** [comment]
Ther problem still is with the YouTube Data API keys quota: https://github.com/Taapat/enigma2-plugin-youtube/issues/68

The best solution for users at this moment is to create their own keys in Google Cloud Console.
Install latest plugin version from here: http://taapat.ho.ua/enigma2-plugin-youtube/

Save your keys in file /etc/enigma2/YouTube.key
Restart enigma.
In plugin settings disable 'Log in to your YouTube account when plugin starts'.
After that enable and login with your changed keys.

**Comment by kalehrl** [comment]
I did so. But still doesn't work.
I added my own keys to /etc/enigma2/YouTube.key

**Comment by Taapat** [comment]
And you did autentification with your keys?

**Comment by kalehrl** [comment]
I installed the version of the plugin from Jan 27 and added my keys in YouTubeUi.py and youtube works fine. With the latest version and my keys in /etc/enigma2/YouTube.key, there is this error.

**Comment by toni185** [comment]
I couldn't also get it to work so I uninstalled all and installed latest version -March 26- update and now automatically even logged into my account and all works great

**Comment by Taapat** [comment]
If you do not authenticate you are not using your own keys.
You are using a refresh token from keys that used before.

**Comment by kalehrl** [comment]
> In plugin settings disable 'Log in to your YouTube account when plugin starts'.
> After that enable and login with your changed keys.
Enigma2 crashed after this.
[enigma2_crash_1585309825.log](https://github.com/Taapat/enigma2-plugin-youtube/files/4393295/enigma2_crash_1585309825.log)

**Comment by Taapat** [comment]
I alredy fix this but I create a package in the evening: https://github.com/Taapat/enigma2-plugin-youtube/commit/0b315af077ac0931de410bec47b803c546a8f8cc
You can replace file in plugin folder: https://raw.githubusercontent.com/Taapat/enigma2-plugin-youtube/master/src/YouTubeUi.py

But this GSOD indicates that you are having trouble connecting to google.

**Comment by kalehrl** [comment]
> 
> 
> I alredy fix this but I create a package in the evening: [0b315af](https://github.com/Taapat/enigma2-plugin-youtube/commit/0b315af077ac0931de410bec47b803c546a8f8cc)
> You can replace file in plugin folder: https://raw.githubusercontent.com/Taapat/enigma2-plugin-youtube/master/src/YouTubeUi.py
> 
> But this GSOD indicates that you are having trouble connecting to google.

I installed it this morning but when I try to perform authentication from within the YouTube menu, the message 'There was an error' pops up. There is no enigma2 crash just this error.

**Comment by Taapat** [comment]
Yes I fix GSOD, but as I write you having some problems on reciever connecting to google.
Try create enigma debug log. Maybe you can see the reason in it.

**Comment by kalehrl** [comment]
[enigma2 log.txt](https://github.com/Taapat/enigma2-plugin-youtube/files/4396918/enigma2.log.txt)
Here is the log

**Comment by toni185** [comment]
To me was working great with newest update but now again from today not working. Have you changed something?

**Comment by toni185** [comment]
I'm having problems, I deleted plugin and everything, installed latest update. Get error in creating list.

So I removed my user, made keys on the Google API put them in YouTube.key in etc enigma2 and restarted receiver. Same peoble. Error in creating list. Nothing changes for me.

Can you help? I'm having this problem for 2 weeks or more.. what am I doing wrong?

**Comment by grzech14** [comment]
Hi,
I installed enigma2-plugin-extensions-youtube_h1+git440+e958b6a-r0.0_all and put my keys into /etc/enigma2/YouTube.key

After disabling ‘Log in to your YouTube account when plugin starts' and re-enabling it to login to google/device page, the plugin crashes after few seconds – too short time to type the code on google page. Any support is welcome. 
From the crash log file:

REMOVE Peer vuzero4k
REMOVE Peer vuzero4k
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/YouTube/YouTubeUi.py", line 1602, in splitTaimerStop
    refreshToken, retryInterval = self.oauth.get_new_token()
TypeError: 'NoneType' object is not iterable

**Comment by Taapat** [comment]
Thx for report. I fix GSOD there: https://github.com/Taapat/enigma2-plugin-youtube/commit/a17dd3132259eb72bffb919d15542c11d728d585

But it looks like you're having trouble connecting to google.
After the fix GSOD will no longer be, but probably you will have some other problem to authorize the plugin.

**Comment by toni185** [comment]
> And you did autentification with your keys?

How do we do authentication? Cause I have keys but don't know what next

**Comment by grzech14** [comment]
Thx for fix, but it still crashes,now the error is:
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/YouTube/YouTubeUi.py", line 1602, in splitTaimerStop
    refreshToken, retryInterval = self.oauth.get_new_token()
  File "/usr/lib/enigma2/python/Plugins/Extensions/YouTube/OAuth.py", line 72, in get_new_token
    response = self.conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1108, in getresponse
httplib.ResponseNotReady

 STB is able to connect to google as it displays pairing code on the screen.

**Comment by toni185** [comment]
> If you do not authenticate you are not using your own keys.
> You are using a refresh token from keys that used before.

Just to say it is working for me! It said unauthorized app warning again, went into advanced options, agreed all that and now finally no error logged in and working under my keys! Great! 👏

**Comment by Taapat** [comment]
@grzech14 I hope I fixed your GSOD in a not nice way: https://github.com/Taapat/enigma2-plugin-youtube/commit/e98c39c1971490a19d872c8f4ff7b8a63bedf6e6
But you can see in the crash log that there is some problem to connect on googleapis.
I can't observe such a problem with myself, so I hope that everything is fine with the code.

**Comment by grzech14** [comment]
@Taapat  Thanks a lot. I confirm it is working now and private keys are working too :)

**Comment by budiarno** [comment]
> <   736.255> [YouTube] Selected: most_viewed
> <   736.414> [YouTubeApi] error in get response
> <   736.414> [YouTubeApi] error in get response, errorcode Unknown
> <   736.417> [Skin] Processing screen: MessageBox
> <   736.424> warning, skin is missing element WarningPixmap in <class 'Screens.MessageBox.MessageBox'>(There was an error in creating entry list!
> Maybe try other feeds...)<   736.424>

I got that error even after adding keys to YouTube.key. Any hints would be very appreciated. Thank you.

**Comment by Taapat** [comment]
1. Or you use a text editor that supports linux line ending for editing YouTube.key?
2. Do you make a re-authentication (by entering and confirming the plugin code) after changing the keys?

**Comment by budiarno** [comment]
I'm so sorry, it was only caused by the region. After switching to Indonesia, everything just works fine. Thank you.
