### ISSUE TITLE
Response Error

### ISSUE THREAD

**Issue by thawtes** [Taapat/enigma2-plugin-youtube#68]
get lists and all data not work

Error
[YouTubeApi] error in response 403

**Comment by thawtes** [comment]
now work !
interesting ...

**Comment by thawtes** [comment]
not work again !
why is this problem caused?

**Comment by S4iyan3lit3** [comment]
![Feed_Error](https://user-images.githubusercontent.com/39001829/76179077-df372a80-61b9-11ea-92c4-5e332b2961cf.jpg)

**Comment by Taapat** [comment]
Sorry for late answer.
There is a problem with the YouTube Data API keys quota.
For the plugin google it limits it to 1.25 million in a day and it ends very quickly.

The best solution for users at this moment is to create their own keys in Google Cloud Console, replace them in plugin and use.

**Comment by Taapat** [comment]
You need create and change in YouTubeUi.py with own API_KEY, YOUTUBE_API_CLIENT_ID, YOUTUBE_API_CLIENT_SECRET

https://github.com/Taapat/enigma2-plugin-youtube/blob/master/src/YouTubeUi.py#L129-L131

**Comment by thawtes** [comment]
> 
> 
> Sorry for late answer.
> There is a problem with the YouTube Data API keys quota.
> For the plugin google it limits it to 1.25 million in a day and it ends very quickly.
> 
> The best solution for users at this moment is to create their own keys in Google Cloud Console, replace them in plugin and use.

yes right...

can you add these fields to config lists ?

**Comment by S4iyan3lit3** [comment]
Greetings!

Yes!

Confirm!

It's working when the proper API settings included in YouTubeUI.py..

Need to create menu entry,where is possible to define these data without editing source code all time..

...

configlist.append(getConfigListEntry(_('YouTube API Key:'),
			config.plugins.YouTube.refreshToken,
			_('Specify the YouTube API_KEY.')))

configlist.append(getConfigListEntry(_('YouTube API Client ID:'),
			config.plugins.YouTube.refreshToken,
			_('Specify the YouTube API_CLIENT_ID.')))

configlist.append(getConfigListEntry(_('YouTube API CLIENT SECRET:'),
			config.plugins.YouTube.refreshToken,
			_('Specify the YouTube API_CLIENT_SECRET.')))

...

![1](https://user-images.githubusercontent.com/39001829/76475718-1c8cf980-6400-11ea-8d45-df7c5897a156.jpg)

**Comment by Taapat** [comment]
Hi,
YOUTUBE_API_CLIENT_ID is very long.
I don't think it is possible to enter it with a remote without errors.
I plan to create a separate file for the keys in the enigma config folder.
It will be saved by creating an enigma beckup and will be easier to enter keys.
In addition, developers will be able to use their own keys and reduce the load on plugin keys.

**Comment by petrkr** [comment]
> Hi,
> YOUTUBE_API_CLIENT_ID is very long.
> I don't think it is possible to enter it with a remote without errors.
> I plan to create a separate file for the keys in the enigma config folder.
> It will be saved by creating an enigma backup and will be easier to enter keys.
> In addition, developers will be able to use their own keys and reduce the load on plugin keys.

Then you can read it from filesystem. like /etc/enigma2/youtube-plugin.conf and I do not know if there can be interaction with web server, but if so, it can be set also through OpenWebIF

**Comment by toni185** [comment]
I made all 3 API_KEY, YOUTUBE_API_CLIENT_ID, YOUTUBE_API_CLIENT_SECRET and put them in  YouTubeUi.py and still not working. Maybe I done something wrong, can yo make short video of creating those keys?

**Comment by petrkr** [comment]
> I made all 3 API_KEY, YOUTUBE_API_CLIENT_ID, YOUTUBE_API_CLIENT_SECRET and put them in YouTubeUi.py and still not working. Maybe I done something wrong, can yo make short video of creating those keys?

be sure you deleted pre-compiled version ending "pyo" or "pyc". Because sometimes interpreter prefer compiled version instead .py one.

so if you have YouTubeUi.pyc (or YouTubeUi.pyo) delete it.

**Comment by toni185** [comment]
Yes I tried deleting youTubeui.pyo but still same thing. When creating API client id I chose Tv and other input maybe I should have chosen other option?  API key is easy but this other Client Id has many options to choose

**Comment by petrkr** [comment]
You should do it at developer console, there is not more things... I actually do not understand why youtube plugin needs both, API and OAuth2... but both you can generate in google developer console.

**Comment by petrkr** [comment]
![image](https://user-images.githubusercontent.com/6428351/77238239-cd4c8300-6bce-11ea-8ea9-8836062067b7.png)

**Comment by toni185** [comment]
Ok as "type I chose TV and Limited Input. I'll try with 'other' maybe that was problem

**Comment by toni185** [comment]
![Screenshot_2020-03-21-23-57-06-366_com android chrome](https://user-images.githubusercontent.com/61566623/77238384-b9555100-6bcf-11ea-838c-5deacdee2388.jpg)

I have this options to choose from

**Comment by Taapat** [comment]
After the keys change in plugin you need to re-login to google to use your keys.
In settings disable login.
After that enable and login with your changed keys.

**Comment by toni185** [comment]
To me is finally working. First I uninstalled the plugin and yesterday I saw new version is uploaded. 
I installed latest version March 26 and all works 👌

**Comment by toni185** [comment]
Well thing is I uninstalled plugin cause I couldn't make it work. And no folder was left or youtubeui.py unless it's in 2 places. And when I put new plugin my user was already logged in. Don't know how

**Comment by Taapat** [comment]
Refresh token is saved ijn e igma settings. So you if you not authenticate you are  are using a refresh token from keys that used before.

**Comment by toni185** [comment]
Just a question. API keys must be inserted in etc/enigma2/YouTube.key ? Cause I find this file has all 3 api keys?

I used to insert my keys in usr/lib/python/extensions/YouTube/youtubeui.py

**Comment by toni185** [comment]
I installed newest update from April.. inserted my keys in YouTube key and get error unauthorized app. 

And after it I'm logged in but still error can't get list.. so even with keys inserted it's not working..

**Comment by Taapat** [comment]
If you not authorized your keys you of course get unauthorized app warning.
Or you ignore this warning and authorize plugin using your keys?

**Comment by toni185** [comment]
But I made the API keys, all of them, don't know where to authorize them. 
Also the thing is after I delete YouTube.key and remove plugin and install it again it's working all and I'm automatically logged in somehow..
Ofcourse until the user limit is reached and then can't after some time see videos again...

**Comment by Taapat** [comment]
You cannot create Client IDs and Client secret keys without configuring the OAuth consent screen.
When you configured the OAuth consent screen you could read a warning about unverified app screen until you have verified your app.

I want to point that you don't need to do the verification, you just received a warning about it.
If you use your keys, you can be sure that by using them no one will steal your data and you can ignore this warning.

**Comment by thawtes** [comment]
Everything works fine and works well after last commits made thanks @Taapat

**Comment by Zhekos555** [comment]
I have installed the latest version from 2020-04-11, installed API keys and authorised them. The problem is that plugin opens some videos, with the most music videos I'm getting "Signature extraction failed! 
Any ideas what could be wrong?

**Comment by Taapat** [comment]
I assume these are official videos.
Try the latest version of the plugin with today's changes.

**Comment by Zhekos555** [comment]
> I assume these are official videos.
> Try the latest version of the plugin with today's changes.

Installed the latest version and everything is back to normal, plugin plays all videos. Thanks Taapat!
