### ISSUE TITLE
erro feeds

### ISSUE THREAD

**Issue by rikardo17** [Taapat/enigma2-plugin-youtube#69]
hello friend since some time ago my youtube stopped giving right says "error in the feeds" when I do research, do you know how I can solve this? I have openatv 6.4 mips

I await reply thank you

**Comment by Taapat** [comment]
Or you try create and use your own API keys?
https://github.com/Taapat/enigma2-plugin-youtube/issues/67
https://github.com/Taapat/enigma2-plugin-youtube/issues/68

**Comment by rikardo17** [comment]
I don't know, do it buddy

**Comment by rikardo17** [comment]
How can I do this? can you help me?

**Comment by Taapat** [comment]
https://github.com/jdf76/plugin.video.youtube/wiki/Personal-API-Keys

**Comment by rikardo17** [comment]
thanks

**Comment by fairbird** [comment]
@rikardo17 
You can learn from this video (It is very easy)  
https://www.youtube.com/watch?v=3jZ5vnv-LZc

**Comment by rikardo17** [comment]
I will try then stop by here to say thank you very much

**Comment by rikardo17** [comment]
I was resolved thank you very much
