### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cattard1985** [Taapat/enigma2-plugin-youtube#72]
I am receiving this error"there  was an error in creating entry list! maybe try other feeds" as i click on a searched item. Using vu+ zero, open atv 6.4 enigma 2

**Comment by Taapat** [comment]
The problem is with the YouTube Data API keys quota.
Please create and use your own keys: https://github.com/Taapat/enigma2-plugin-youtube/issues/67

**Comment by Taapat** [comment]
The YouTube Data API keys quota is now sufficient.
I think I can close this issue.
