### ISSUE TITLE
Video Url 

### ISSUE THREAD

**Issue by Freak7x7** [Taapat/enigma2-plugin-youtube#73]
Hallo, when I ll play a Video Music there comes an error
"Video Url konnte nicht extrahiert werden Signatur extraction failed" 
I searched for the error in Google but nothing found. 
STB: Gigablue UHD UE 4K Image HDF V6.5 #27 youtube dll1.2
Thanks

**Comment by Taapat** [comment]
Try latest plugin version from there: http://taapat.ho.ua/enigma2-plugin-youtube/

**Comment by Freak7x7** [comment]
Thanks Man you are the Best!!! It's works fine..
