### ISSUE TITLE
Favoriten List 

### ISSUE THREAD

**Issue by Freak7x7** [Taapat/enigma2-plugin-youtube#75]
Hello I have a problem  when I want to add a video to favorites I get the error message "Information" error. And when I select the favorites "Error creating the list!" Try again later

Thanks 

Gigablue UHD ue 4k Image Hdfreaks 6.5 35

**Comment by Taapat** [comment]
Hi!
Are you really using Favorites?
A couple days ago I was thinking about removing Favorites in plygin.
I don't use it myself and think that youtube has not supported the special Favorites palylist for a long time.
But I can be wrong.

**Comment by Freak7x7** [comment]
Aso ok, then it's fine thanks anyway
