### ISSUE TITLE
there is a problem on live broadcasts

### ISSUE THREAD

**Issue by suatsuphi** [Taapat/enigma2-plugin-youtube#76]
hi,
there is a problem on live broadcasts that sound and video synchronization. video comes back of sound. there is a delay for video 
could you fix it ?

**Comment by Taapat** [comment]
Ho,
What is your receiver and image?
The plugin itself does not play anything. Plugin only extract link wich played by enigma player.
Therefore, a lot depends on how well the player works in your receiver.
Of course, plugin may be try offer choose another link, if that exists.
Have you tried to specify a lower resolution in the settings?

**Comment by suatsuphi** [comment]
Hi,
Gigabule quad and opendroid 6.8
"The plugin itself does not play anything. Plugin only extract link wich played by enigma player."
thank you for information.
"Have you tried to specify a lower resolution in the settings?" 
I have just tried it. I've got same result. 
ip tv is working? I suppose there is a problem of video codec.

**Comment by Taapat** [comment]
Maybe you can give specific examples that don't work.
Everything what I try works for me.

**Comment by suatsuphi** [comment]
I suppose video player of opendroid 6.8 doesn't support video codec of youtube.
is it possibble ? can I update it that video codec?

**Comment by suatsuphi** [comment]
I can't make fast forward of the video. It is not live broadcast.
