### ISSUE TITLE
I can't install it git486

### ISSUE THREAD

**Issue by suatsuphi** [Taapat/enigma2-plugin-youtube#79]
Hi,
I can't install new version
enigma2-plugin-extensions-youtube_h1+git486+1f8bc35-r0.0_all.ipk
I have Gigabule quad and opendroid 6.8

**Comment by Taapat** [comment]
Hi,
What mean I can't install the new version?
Are you getting an error when installing the ipk package?

**Comment by suatsuphi** [comment]
yes, it is. 

Welcome to opendroid for gbquad
opendroid 6.8 gbquad

gbquad login: root
Last login: Tue May 19 14:30:04 +03 2020 on pts/0
root@gbquad:~# opkg install /tmp/*.ipk
Refusing to load file '/tmp/enigma2-plugin-extensions-youtube_h1+git486+1f8bc35-r0.0_all.ipk' as it matches the installed version of enigma2-plugin-extensions-youtube (h1+git486+1f8bc35-r0.0).
Unknown package '/tmp/enigma2-plugin-extensions-youtube_h1+git486+1f8bc35-r0.0_all.ipk'.
Collected errors:
 * opkg_solver_install: Cannot install package /tmp/enigma2-plugin-extensions-youtube_h1+git486+1f8bc35-r0.0_all.ipk.

**Comment by Taapat** [comment]
As you can see in the log, you already installed the latest version:

> Refusing to load file '/tmp/enigma2-plugin-extensions-youtube_h1+git486+1f8bc35-r0.0_all.ipk' as it matches the installed version of enigma2-plugin-extensions-youtube (h1+git486+1f8bc35-r0.0).

**Comment by suatsuphi** [comment]
thank you, but there is no folder in Extensions Folder > /usr/lib/enigma2/python/Plugins/Extensions 

how can I fix it ? could you help about it ?

**Comment by Taapat** [comment]
I assume you've installed the ipk file, but after that
manually deleted folder.
```
opkg remove enigma2-plugin-extensions-youtube
opkg install /tmp/enigma2-plugin-extensions-youtube_h1+git486+1f8bc35-r0.0_all.ipk
```

**Comment by suatsuphi** [comment]
thank you it is ok now.
