### ISSUE TITLE
There is no result for Search live boardcasts

### ISSUE THREAD

**Issue by suatsuphi** [Taapat/enigma2-plugin-youtube#80]
Hi,
There is no result for Search live boardcasts. 
I get this error message when I search anything.
There was an error in creating entry list! Maybe list try other feeds.
It is work for other tab. but I cant search on live boardcasts

**Comment by suatsuphi** [comment]
hi,
I found why it is.
If exclude restricted content - yes, I cant search on live boardcast

**Comment by Taapat** [comment]
Hi,
Restricted content in search results is determined by google.
I can't influence it. Possible live boardcasts which you are looking includes google restricted content.

**Comment by suatsuphi** [comment]
I dont know why... I can result for live but if I search 'canlı', there is no result. 
its mean 'live' in turkish

**Comment by suatsuphi** [comment]
I installed new version https://opendroid.org/ 7.0 now it is working thank you and I hope you will add subtitled version
