### ISSUE TITLE
Crash when downloading a video

### ISSUE THREAD

**Issue by ozone1864** [Taapat/enigma2-plugin-youtube#81]
Dear @Taapat ,

When I try to download a video from youtube and then checking the active download page.
My system crash. Any idea ?
Hardware: Zgemma H9S
Software: OpenAtv 6.3 latest version stable

Regards,

**Comment by ozone1864** [comment]
I can attach a crash log if this might help you.
Thanks

**Comment by Taapat** [comment]
Please attach a crash log.

**Comment by ozone1864** [comment]
Hi,

Kindly find attached log file.
Please note that the problem is happening like
everytime I want to download a video and sometimes
when I watch without downloading.

Thank you,

[enigma2_crash_1590392348.log](https://github.com/Taapat/enigma2-plugin-youtube/files/4675886/enigma2_crash_1590392348.log)

**Comment by ozone1864** [comment]
[enigma2_crash_1590395386.log](https://github.com/Taapat/enigma2-plugin-youtube/files/4676193/enigma2_crash_1590395386.log)

**Comment by Taapat** [comment]
Hi,
Looks like this is a bug in OpenAtv in Tools/Downloader.py
In this commit captain changed the function pageEnd in HTTPProgressDownloader and added to it from OpenPli using of variable self.end_callback: https://github.com/openatv/enigma2/commit/917eb8ca226b119a93ac32a2933e3f44be420f40


Unfortunately, he missed that all changes must be like this, where self.end_callback is defined on init: https://github.com/OpenPLi/enigma2/commit/bcfdaae889cdf1b3f592bc7fb5e1590649f842e7

**Comment by ozone1864** [comment]
Issue must be opened under openatv/enigma2

**Comment by Taapat** [comment]
Yes.
I already wrote a comment at the problematic commit on openatv.
But for a faster solution you can open issuse on openatv.

**Comment by ozone1864** [comment]
Thank you I will check with captain
Try to comment on the issue I will open

**Comment by Taapat** [comment]
I think we can close this issue after https://github.com/openatv/enigma2/commit/14fec2912b73efd7104859203e2042461d1b1b2e

**Comment by ozone1864** [comment]
@Taapat updated to the latest version today of openatv 6.3. 
Again a crash check the log plz
[enigma2_crash_1590488006.log](https://github.com/Taapat/enigma2-plugin-youtube/files/4681455/enigma2_crash_1590488006.log)
[enigma2_crash_1590487762.log](https://github.com/Taapat/enigma2-plugin-youtube/files/4681456/enigma2_crash_1590487762.log)
