### ISSUE TITLE
Zgemma H9S service hisilicon

### ISSUE THREAD

**Issue by ozone1864** [Taapat/enigma2-plugin-youtube#82]
Dear @Taapat ,
Zgemma H9S comes with embedded player "service hisilicon".
The problem is when using serviceapp and the playback system is set original no video or audio on the plugin, sometimes video plays but without audio.
BUT if we change the playback system to exteplayer3 the plugin works normal any solution ? 
And if the problem is from service hisilicon can you explain briefly to forward the issue.
Thank you,
Best Regards,

**Comment by Taapat** [comment]
https://github.com/Taapat/enigma2-plugin-youtube/issues/60#issuecomment-528715023

Zgemma has introduced a suburi parameter in their service hisilicon plugin, but only to split the playback link.
It is necessary to implement suburi for playing two parallel streams.

**Comment by ozone1864** [comment]
Thank you
Will forward to hisilicon
