### ISSUE TITLE
remember last position

### ISSUE THREAD

**Issue by ahmedsaad151** [Taapat/enigma2-plugin-youtube#90]
can you add remember last position
plz?

**Comment by Taapat** [comment]
Sorry, I don't understand.
The last position where?

**Comment by ahmedsaad151** [comment]
I mean when I was playing any video and exit from it
And want to see the video again
The plugin starts from the beginning
It doesn't remember last position that I stopped the video
This option is similar to remember last position in e2iplayer configuration

في خميس، ٢ يوليو، ٢٠٢٠ ٨،٠٧ ص Madars Auns <notifications@github.com> كتب:

**Comment by Taapat** [comment]
I'll think about it.
I would like to keep this plugin as simple as possible.
To realize your request plugin should save playing video and play position on exit.
After that on startup find this video and seek to this position.
Knowing that on gstreamer seek works very poorly I anticipate problems with the use of this feature in many clips.

**Comment by Taapat** [comment]
Seek does not work on gstreamer in dash mp4 formats, therefore resume playback is only offered on non dash mp4 streams or using exteplayer!

**Comment by ahmedsaad151** [comment]
Ok I will try

في أربعاء، ٨ يوليو، ٢٠٢٠ ٩،٢٢ م Madars Auns <notifications@github.com> كتب:

**Comment by Taapat** [comment]
I hope you understand my note about exteplayer: https://github.com/Taapat/enigma2-plugin-youtube/commit/f534c54e675b890aff80e415023b98fb69ad6ee7
