### ISSUE TITLE
Recent feed does not display all recent videos

### ISSUE THREAD

**Issue by artseluiko** [Taapat/enigma2-plugin-youtube#92]
I have 61 youtube subscriptions. When I navigate to 'My Feeds'->'My Subscriptions'->'Recent' not all recent videos are displayed here. Some of them are skipped. It's easy to understand if compare recent feed entries with a "Subscriptions" youtube web page. If I navigate directly to the channel all channel videos are displayed even the skipped ones

**Comment by Taapat** [comment]
Yes, I've missed that recent videos are only showing only from so many subscriptions which are in search results value.
I will look at this problem.
