### ISSUE TITLE
#Collected_Error_In_Updates..

### ISSUE THREAD

**Issue by S4iyan3lit3** [Taapat/enigma2-plugin-youtube#98]
Greetings!

In first let me sorry for disturbing..

I was recognize some cumulative error in updates after rev_553...

So only the rev_553 working properly on VTI images..Updates after this revision are out of luck..

After downgrading to rev_553, YT_Plugin again working properly!

(Receiver VU+ Zero 4k and VU+ Solo 2 with Image Version: VTI_14.0.6)

Please Check Attached Screenshots!

Have God-Blessed Good Day!

Regards!

![1](https://user-images.githubusercontent.com/39001829/92021878-b9e73b80-ed5a-11ea-93df-d0775c70edc2.jpg)
![2](https://user-images.githubusercontent.com/39001829/92021881-b9e73b80-ed5a-11ea-922c-2a0bec971862.jpg)
![3](https://user-images.githubusercontent.com/39001829/92021879-b9e73b80-ed5a-11ea-9252-2bbd7a21b122.jpg)

**Comment by Taapat** [comment]
Thanks for the report!

This is obviously related to the Openvix compatibility patch offered by @Huevos: https://github.com/Taapat/enigma2-plugin-youtube/commit/98d89e9fde2ac8426e8587b27ffc7efcaed920c9
I will think or it can be created in a different way.
Probably i need to remove VKeyIcon.

**Comment by Huevos** [comment]
By the way what skin is being used?

**Comment by Huevos** [comment]
Thanks.
