### ISSUE TITLE
#YT_Search_Bug_Still_Persist..

### ISSUE THREAD

**Issue by S4iyan3lit3** [Taapat/enigma2-plugin-youtube#99]
Greetings!

In first let me sorry for disturbing..

Next..Thank You So Much for "Quick Fix" of the skin compatibility issue on rev_568 for VTI_Images! I can confirm,it's now OK! (check screenshot!)

...

Unfortunately there is still persist one of error in update rev_568..

The search function is still not working...only in rev_553 but after this revision not working anymore..

Please Check It Out if possible!

And Yes,The API_Keys are proper..as I wroted,when i downgrade to rev_553 everything works fine!

Thank You So Much For Patience,Discretion!

(Receiver VU+ Zero / VU+ Zero 4k / VU+ Solo 2 with Image Version: VTI_14.0.6 / Skin: Attile_HD)

Please Check Attached Screenshots!

Have God-Blessed Good Day!

Regards!

![1](https://user-images.githubusercontent.com/39001829/92285070-b216cb00-ef03-11ea-9ca4-9d3ee484f03f.jpg)
![2](https://user-images.githubusercontent.com/39001829/92285076-b511bb80-ef03-11ea-9ecf-2b1f0a3cb75e.jpg)

**Comment by Taapat** [comment]
After 553, I changed the default search region and language setting.
In one issue, the user stated that he solved the search problem after setting the correct search region in plugin settings.
If that doesn't help, try try to repeat plugin authentication.

**Comment by S4iyan3lit3** [comment]
Greetings!

Thank You So Much For Your Reply,but I found out a solution myself!

I'll share it with others!

/////////////////////////////////////////////////////////////////////////////////////////////

VTI_Users_Actual_Quick_Solution_For_YT_Plugin_rev_570_and_above++:

1. ssh_login_as_root

2. cp /etc/enigma/settings /etc/enigma/settings.BCK

3. nano_or_vi /etc/enigma/settings

4. remove all lines "config.plugins.YouTube.*" from settings file...

5. add these lines only:

config.plugins.YouTube.searchLanguage=
config.plugins.YouTube.searchRegion=
config.plugins.YouTube.safeSearch=none
config.plugins.YouTube.maxResolution=18
config.plugins.YouTube.searchResult=8
config.plugins.YouTube.saveHistory=false

6. save settings file and quit editor

7. # reboot -f

~nJ0Y~

\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\


Regards!

Have God-Blessed Good Day!

By3~
